In [3]:
!pip install -q gdown

FOLDER_ID = "1OvtUfbhoOjppGK9T_pmH7bYsGbj2Tu9i"
PASTA_PDFS = "/content/pdfs_aula04"

!gdown --folder "https://drive.google.com/drive/folders/{FOLDER_ID}" -O {PASTA_PDFS}

Retrieving folder contents
Processing file 1aABWdLBWjRj1-M3Xtj1KPxSXYDOFKauo attention_is_all_you_need.pdf
Processing file 194xNt2-lOiVN_w9mIlpXjsp-dPIAvxll bert_pretraining.pdf
Processing file 1qe_Dr1ecyfwXaWFnOd4b7pPsi4gih8zN bioetica_e_ia.pdf
Processing file 1bM4uPI_EJjEn5OdenTAVxupcjvDrzqyK escrita_academica_ia.pdf
Processing file 1Vg-r2KHeMsFH0aqOaHQYfbY48PWPcXTn gpt3_language_models.pdf
Processing file 1_BDRqG3JyU95y9HSnDdFt9wmRkN7hzjY gpt4_technical_report.pdf
Processing file 1fKZAWcexIZghV6TCus8aN38f7bfSFJMa instruct_gpt.pdf
Processing file 1n8RM5Ex9q0tGl1vUV3K8IBD6vSAg-s3y llama_foundation_models.pdf
Processing file 1gzYvW-IDC0QMzdUR5FgnFQBcIOyLjAeE lora_low_rank_adaptation.pdf
Processing file 1mTD8QNUlkjfPYUD5-rGEwlNX4Hfgertn retrieval_augmented_generation.pdf
Processing file 1_AfXRP6bGEWcxvvCHBstzYxc4pzfYn_C scaling_laws_llm.pdf
Processing file 104p-oy8TVXb_ksHOto86dAhJTHptT29k twitter_algoritmo.pdf
Retrieving folder contents completed
Building directory structure
Building directory structure completed
Downloading...
From: https://drive.google.com/uc?id=1aABWdLBWjRj1-M3Xtj1KPxSXYDOFKauo
To: /content/pdfs_aula04/attention_is_all_you_need.pdf
100% 2.22M/2.22M [00:00<00:00, 197MB/s]
Downloading...
From: https://drive.google.com/uc?id=194xNt2-lOiVN_w9mIlpXjsp-dPIAvxll
To: /content/pdfs_aula04/bert_pretraining.pdf
100% 775k/775k [00:00<00:00, 125MB/s]
Downloading...
From: https://drive.google.com/uc?id=1qe_Dr1ecyfwXaWFnOd4b7pPsi4gih8zN
To: /content/pdfs_aula04/bioetica_e_ia.pdf
100% 401k/401k [00:00<00:00, 105MB/s]
Downloading...
From: https://drive.google.com/uc?id=1bM4uPI_EJjEn5OdenTAVxupcjvDrzqyK
To: /content/pdfs_aula04/escrita_academica_ia.pdf
100% 769k/769k [00:00<00:00, 136MB/s]
Downloading...
From: https://drive.google.com/uc?id=1Vg-r2KHeMsFH0aqOaHQYfbY48PWPcXTn
To: /content/pdfs_aula04/gpt3_language_models.pdf
100% 6.77M/6.77M [00:00<00:00, 56.4MB/s]
Downloading...
From: https://drive.google.com/uc?id=1_BDRqG3JyU95y9HSnDdFt9wmRkN7hzjY
To: /content/pdfs_aula04/gpt4_technical_report.pdf
100% 5.25M/5.25M [00:00<00:00, 55.8MB/s]
Downloading...
From: https://drive.google.com/uc?id=1fKZAWcexIZghV6TCus8aN38f7bfSFJMa
To: /content/pdfs_aula04/instruct_gpt.pdf
100% 1.80M/1.80M [00:00<00:00, 206MB/s]
Downloading...
From: https://drive.google.com/uc?id=1n8RM5Ex9q0tGl1vUV3K8IBD6vSAg-s3y
To: /content/pdfs_aula04/llama_foundation_models.pdf
100% 727k/727k [00:00<00:00, 111MB/s]
Downloading...
From: https://drive.google.com/uc?id=1gzYvW-IDC0QMzdUR5FgnFQBcIOyLjAeE
To: /content/pdfs_aula04/lora_low_rank_adaptation.pdf
100% 1.61M/1.61M [00:00<00:00, 123MB/s]
Downloading...
From: https://drive.google.com/uc?id=1mTD8QNUlkjfPYUD5-rGEwlNX4Hfgertn
To: /content/pdfs_aula04/retrieval_augmented_generation.pdf
100% 885k/885k [00:00<00:00, 153MB/s]
Downloading...
From: https://drive.google.com/uc?id=1_AfXRP6bGEWcxvvCHBstzYxc4pzfYn_C
To: /content/pdfs_aula04/scaling_laws_llm.pdf
100% 2.49M/2.49M [00:00<00:00, 182MB/s]
Downloading...
From: https://drive.google.com/uc?id=104p-oy8TVXb_ksHOto86dAhJTHptT29k
To: /content/pdfs_aula04/twitter_algoritmo.pdf
100% 1.03M/1.03M [00:00<00:00, 104MB/s]
Download completed

In [5]:
import os

PASTA_PDFS = "/content/pdfs_aula04"
PASTA_RESULTADOS = "/content/drive/MyDrive/Residencia_RAG/results"

os.makedirs(PASTA_RESULTADOS, exist_ok=True)

print(os.listdir(PASTA_PDFS))

['scaling_laws_llm.pdf', 'twitter_algoritmo.pdf', 'bioetica_e_ia.pdf', 'escrita_academica_ia.pdf', 'llama_foundation_models.pdf', 'bert_pretraining.pdf', 'gpt3_language_models.pdf', 'instruct_gpt.pdf', 'gpt4_technical_report.pdf', 'retrieval_augmented_generation.pdf', 'lora_low_rank_adaptation.pdf', 'attention_is_all_you_need.pdf']

In [6]:
PASTA_PDFS = "/content/pdfs_aula04"

PASTA_RESULTADOS = "/content/drive/MyDrive/Residencia_RAG/results"   # resultados sempre no seu Drive

os.makedirs(PASTA_RESULTADOS, exist_ok=True)

print(os.listdir(PASTA_PDFS))

['scaling_laws_llm.pdf', 'twitter_algoritmo.pdf', 'bioetica_e_ia.pdf', 'escrita_academica_ia.pdf', 'llama_foundation_models.pdf', 'bert_pretraining.pdf', 'gpt3_language_models.pdf', 'instruct_gpt.pdf', 'gpt4_technical_report.pdf', 'retrieval_augmented_generation.pdf', 'lora_low_rank_adaptation.pdf', 'attention_is_all_you_need.pdf']

In [7]:
!pip install -q langchain langchain-community langchain-text-splitters
!pip install -q pymupdf4llm          # extração de PDF para Markdown preservando estrutura
!pip install -q langchain-huggingface sentence-transformers
!pip install -q nltk tiktoken

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 34.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 52.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.4/69.4 kB 4.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 5.8 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.4/176.4 kB 8.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.8/25.8 MB 68.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.9/42.9 MB 18.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.2/19.2 MB 67.3 MB/s eta 0:00:00

In [8]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [9]:
import pymupdf4llm

def extrair_pdf_para_markdown(caminho_pdf: str) -> str:
    """Converte um PDF em texto Markdown preservando estrutura."""
    md_text = pymupdf4llm.to_markdown(caminho_pdf)
    return md_text

In [10]:
pdfs = [f for f in os.listdir(PASTA_PDFS) if f.lower().endswith(".pdf")]
pdfs.sort()
print(f"{len(pdfs)} PDFs encontrados:", pdfs)

markdowns = {}  # nome_documento -> texto markdown

for nome_pdf in pdfs:
    nome_doc = os.path.splitext(nome_pdf)[0]        # ex: "bioetica_e_ia"
    caminho_pdf = os.path.join(PASTA_PDFS, nome_pdf)

    print(f"Convertendo: {nome_pdf}")
    md_text = extrair_pdf_para_markdown(caminho_pdf)
    markdowns[nome_doc] = md_text

    pasta_md = os.path.join(PASTA_RESULTADOS, nome_doc, "markdown")
    os.makedirs(pasta_md, exist_ok=True)
    with open(os.path.join(pasta_md, f"{nome_doc}.md"), "w", encoding="utf-8") as f:
        f.write(md_text)

print("Conversão concluída.")

12 PDFs encontrados: ['attention_is_all_you_need.pdf', 'bert_pretraining.pdf', 'bioetica_e_ia.pdf', 'escrita_academica_ia.pdf', 'gpt3_language_models.pdf', 'gpt4_technical_report.pdf', 'instruct_gpt.pdf', 'llama_foundation_models.pdf', 'lora_low_rank_adaptation.pdf', 'retrieval_augmented_generation.pdf', 'scaling_laws_llm.pdf', 'twitter_algoritmo.pdf']
Convertendo: attention_is_all_you_need.pdf

=== Document parser messages ===
Using Tesseract for OCR processing.
OCR on page.number=2/3.
OCR on page.number=3/4.
OCR on page.number=12/13.
Convertendo: bert_pretraining.pdf

=== Document parser messages ===
Using Tesseract for OCR processing.
OCR on page.number=2/3.
OCR on page.number=3/4.
OCR on page.number=12/13.
Convertendo: bioetica_e_ia.pdf

=== Document parser messages ===
Using Tesseract for OCR processing.
Convertendo: escrita_academica_ia.pdf

=== Document parser messages ===
Using Tesseract for OCR processing.
OCR on page.number=0/1.
OCR on page.number=12/13.
OCR on page.number=13/14.
Convertendo: gpt3_language_models.pdf

=== Document parser messages ===
Using Tesseract for OCR processing.
OCR on page.number=2/3.
OCR on page.number=3/4.
OCR on page.number=4/5.
OCR on page.number=6/7.
OCR on page.number=8/9.
OCR on page.number=10/11.
OCR on page.number=11/12.
OCR on page.number=13/14.
OCR on page.number=14/15.
OCR on page.number=15/16.
OCR on page.number=16/17.
OCR on page.number=18/19.
OCR on page.number=19/20.
OCR on page.number=20/21.
OCR on page.number=21/22.
OCR on page.number=23/24.
OCR on page.number=24/25.
OCR on page.number=26/27.
OCR on page.number=30/31.
OCR on page.number=31/32.
OCR on page.number=37/38.
OCR on page.number=46/47.
OCR on page.number=63/64.
OCR on page.number=64/65.
OCR on page.number=65/66.
OCR on page.number=66/67.
Convertendo: gpt4_technical_report.pdf

=== Document parser messages ===
Using Tesseract for OCR processing.
OCR on page.number=32/33.
OCR on page.number=33/34.
OCR on page.number=34/35.
OCR on page.number=36/37.
OCR on page.number=37/38.
OCR on page.number=38/39.
OCR on page.number=97/98.
e.number=13/14.
OCR on page.number=14/15.
OCR on page.number=15/16.
OCR on page.number=16/17.
OCR on page.number=18/19.
OCR on page.number=19/20.
OCR on page.number=20/21.
OCR on page.number=21/22.
OCR on page.number=23/24.
OCR on page.number=24/25.
OCR on page.number=26/27.
OCR on page.number=30/31.
OCR on page.number=31/32.
OCR on page.number=37/38.
OCR on page.number=46/47.
OCR on page.number=63/64.
OCR on page.number=64/65.
OCR on page.number=65/66.
OCR on page.number=66/67.
Convertendo: instruct_gpt.pdf

=== Document parser messages ===
Using Tesseract for OCR processing.
OCR on page.number=38/39.
OCR on page.number=33/34.
OCR on page.number=34/35.
OCR on page.number=36/37.
OCR on page.number=37/38.
OCR on page.number=38/39.
OCR on page.number=97/98.
Convertendo: llama_foundation_models.pdf

=== Document parser messages ===
Using Tesseract for OCR processing.
OCR on page.number=38/39.
Convertendo: lora_low_rank_adaptation.pdf

=== Document parser messages ===
Using Tesseract for OCR processing.
OCR on page.number=10/11.
OCR on page.number=11/12.
OCR on page.number=24/25.
OCR on page.number=25/26.
Convertendo: retrieval_augmented_generation.pdf

=== Document parser messages ===
Using Tesseract for OCR processing.
OCR on page.number=16/17.
OCR on page.number=11/12.
OCR on page.number=24/25.
OCR on page.number=25/26.
Convertendo: scaling_laws_llm.pdf

=== Document parser messages ===
Using Tesseract for OCR processing.
OCR on page.number=16/17.
Convertendo: twitter_algoritmo.pdf

=== Document parser messages ===
Using Tesseract for OCR processing.
OCR on page.number=11/12.
OCR on page.number=12/13.
OCR on page.number=13/14.
Conversão concluída.

In [12]:
md_com_imagens = pymupdf4llm.to_markdown(
    os.path.join(PASTA_PDFS, "attention_is_all_you_need.pdf"),
    write_images=True,
    image_path="/content/imagens_extraidas"
)

=== Document parser messages ===
Using Tesseract for OCR processing.
OCR on page.number=2/3.
OCR on page.number=3/4.
OCR on page.number=12/13.

In [13]:
from langchain_text_splitters import (
    CharacterTextSplitter,
    RecursiveCharacterTextSplitter,
    NLTKTextSplitter,
    MarkdownHeaderTextSplitter,
)

In [14]:
import tiktoken

encoding = tiktoken.get_encoding("cl100k_base")

def contar_tokens(texto: str) -> int:
    return len(encoding.encode(texto))

In [15]:
def gerar_chunks_teste_1_a_4(texto: str, chunk_size: int):
    splitter = CharacterTextSplitter(
        separator="",            # corta puramente por quantidade de caracteres
        chunk_size=chunk_size,
        chunk_overlap=0,
        length_function=len,
    )
    return splitter.split_text(texto)

In [16]:
def gerar_chunks_teste_5_e_6(texto: str, chunk_overlap: int):
    splitter = CharacterTextSplitter(
        separator="",
        chunk_size=500,
        chunk_overlap=chunk_overlap,   # 50 no teste 5, 200 no teste 6
        length_function=len,
    )
    return splitter.split_text(texto)

In [17]:
def gerar_chunks_teste_7(texto: str):
    splitter = CharacterTextSplitter(
        separator="\n\n",       # quebra de parágrafo
        chunk_size=100000,      # tamanho bem alto: não queremos que ele corte por tamanho,
        chunk_overlap=0,        # só queremos que ele use o \n\n como unidade
    )
    return splitter.split_text(texto)

In [18]:
def gerar_chunks_teste_8(texto: str):
    splitter_sentencas = NLTKTextSplitter()
    sentencas = splitter_sentencas.split_text(texto)
    import nltk
    sentencas = nltk.sent_tokenize(texto)

    chunks = []
    for i in range(0, len(sentencas), 3):
        grupo = sentencas[i:i+3]
        chunks.append(" ".join(grupo))
    return chunks

In [19]:
def gerar_chunks_teste_9(texto: str):
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=100,
        separators=["\n\n", "\n", " ", ""],
    )
    return splitter.split_text(texto)

In [20]:
def gerar_chunks_teste_10(texto_markdown: str):
    headers_to_split_on = [
        ("#", "heading_1"),
        ("##", "heading_2"),
        ("###", "heading_3"),
    ]
    splitter = MarkdownHeaderTextSplitter(headers_to_split_on=headers_to_split_on)
    docs = splitter.split_text(texto_markdown)
    return docs

In [21]:
from langchain_huggingface import HuggingFaceEmbeddings

EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
embedder = HuggingFaceEmbeddings(model_name=EMBEDDING_MODEL)

def gerar_embedding(texto: str):
    return embedder.embed_query(texto)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [22]:
def montar_chunk_dict(chunk_id, document_id, document_name, test_id, strategy,
                       chunk_size, chunk_overlap, texto, embedding, metadata_extra=None):
    metadata = metadata_extra or {}
    return {
        "chunk_id": chunk_id,
        "document_id": document_id,
        "document_name": document_name,
        "test_id": test_id,
        "strategy": strategy,
        "chunk_size": chunk_size,
        "chunk_overlap": chunk_overlap,
        "text": texto,
        "embedding": embedding,
        "metadata": metadata,
    }

In [24]:
import json

def processar_documento(nome_doc: str, texto_md: str, pasta_resultados: str):
    resultados_resumo = []   # para o summary.json

    for cfg in TESTES:
        test_id = cfg["test_id"]

        # 1) gerar os textos dos chunks conforme o teste
        if test_id in [1, 2, 3, 4]:
            textos = gerar_chunks_teste_1_a_4(texto_md, cfg["chunk_size"])
            metadatas = [{} for _ in textos]
        elif test_id in [5, 6]:
            textos = gerar_chunks_teste_5_e_6(texto_md, cfg["chunk_overlap"])
            metadatas = [{} for _ in textos]
        elif test_id == 7:
            textos = gerar_chunks_teste_7(texto_md)
            metadatas = [{} for _ in textos]
        elif test_id == 8:
            textos = gerar_chunks_teste_8(texto_md)
            metadatas = [{} for _ in textos]
        elif test_id == 9:
            textos = gerar_chunks_teste_9(texto_md)
            metadatas = [{} for _ in textos]
        elif test_id == 10:
            docs = gerar_chunks_teste_10(texto_md)
            textos = [d.page_content for d in docs]
            metadatas = [d.metadata for d in docs]

        # 2) gerar embedding + montar o JSON de cada chunk
        chunks_json = []
        tamanhos = []
        for i, (texto_chunk, meta) in enumerate(zip(textos, metadatas), start=1):
            if not texto_chunk.strip():
                continue
            emb = gerar_embedding(texto_chunk)
            chunk_id = f"{nome_doc}_test{test_id:02d}_chunk{i:03d}"
            chunk_dict = montar_chunk_dict(
                chunk_id=chunk_id,
                document_id=nome_doc,
                document_name=f"{nome_doc}.pdf",
                test_id=test_id,
                strategy=cfg["strategy"],
                chunk_size=cfg["chunk_size"],
                chunk_overlap=cfg["chunk_overlap"],
                texto=texto_chunk,
                embedding=emb,
                metadata_extra=meta,
            )
            chunks_json.append(chunk_dict)
            tamanhos.append(len(texto_chunk))

        # 3) salvar o arquivo chunks_embeddings.json do teste
        pasta_teste = os.path.join(pasta_resultados, nome_doc, f"test_{test_id:02d}")
        os.makedirs(pasta_teste, exist_ok=True)
        with open(os.path.join(pasta_teste, "chunks_embeddings.json"), "w", encoding="utf-8") as f:
            json.dump(chunks_json, f, ensure_ascii=False, indent=2)

        # 4) calcular estatísticas para o summary
        num_chunks = len(chunks_json)
        avg_size = sum(tamanhos) / num_chunks if num_chunks else 0
        resultados_resumo.append({
            "test_id": test_id,
            "strategy": cfg["strategy"],
            "chunk_size": cfg["chunk_size"],
            "chunk_overlap": cfg["chunk_overlap"],
            "num_chunks": num_chunks,
            "avg_chunk_size": round(avg_size, 1),
            "min_chunk_size": min(tamanhos) if tamanhos else 0,
            "max_chunk_size": max(tamanhos) if tamanhos else 0,
            "embedding_dimension": len(chunks_json[0]["embedding"]) if chunks_json else 0,
        })

        print(f"  [{nome_doc}] teste {test_id:02d} ({cfg['strategy']}): {num_chunks} chunks")

    return resultados_resumo

In [26]:
import json

def processar_documento(nome_doc: str, texto_md: str, pasta_resultados: str):
    resultados_resumo = []   # para o summary.json

    for cfg in TESTES:
        test_id = cfg["test_id"]

        if test_id in [1, 2, 3, 4]:
            textos = gerar_chunks_teste_1_a_4(texto_md, cfg["chunk_size"])
            metadatas = [{} for _ in textos]
        elif test_id in [5, 6]:
            textos = gerar_chunks_teste_5_e_6(texto_md, cfg["chunk_overlap"])
            metadatas = [{} for _ in textos]
        elif test_id == 7:
            textos = gerar_chunks_teste_7(texto_md)
            metadatas = [{} for _ in textos]
        elif test_id == 8:
            textos = gerar_chunks_teste_8(texto_md)
            metadatas = [{} for _ in textos]
        elif test_id == 9:
            textos = gerar_chunks_teste_9(texto_md)
            metadatas = [{} for _ in textos]
        elif test_id == 10:
            docs = gerar_chunks_teste_10(texto_md)
            textos = [d.page_content for d in docs]
            metadatas = [d.metadata for d in docs]

        chunks_json = []
        tamanhos = []
        for i, (texto_chunk, meta) in enumerate(zip(textos, metadatas), start=1):
            if not texto_chunk.strip():
                continue
            emb = gerar_embedding(texto_chunk)
            chunk_id = f"{nome_doc}_test{test_id:02d}_chunk{i:03d}"
            chunk_dict = montar_chunk_dict(
                chunk_id=chunk_id,
                document_id=nome_doc,
                document_name=f"{nome_doc}.pdf",
                test_id=test_id,
                strategy=cfg["strategy"],
                chunk_size=cfg["chunk_size"],
                chunk_overlap=cfg["chunk_overlap"],
                texto=texto_chunk,
                embedding=emb,
                metadata_extra=meta,
            )
            chunks_json.append(chunk_dict)
            tamanhos.append(len(texto_chunk))

        pasta_teste = os.path.join(pasta_resultados, nome_doc, f"test_{test_id:02d}")
        os.makedirs(pasta_teste, exist_ok=True)
        with open(os.path.join(pasta_teste, "chunks_embeddings.json"), "w", encoding="utf-8") as f:
            json.dump(chunks_json, f, ensure_ascii=False, indent=2)

        num_chunks = len(chunks_json)
        avg_size = sum(tamanhos) / num_chunks if num_chunks else 0
        resultados_resumo.append({
            "test_id": test_id,
            "strategy": cfg["strategy"],
            "chunk_size": cfg["chunk_size"],
            "chunk_overlap": cfg["chunk_overlap"],
            "num_chunks": num_chunks,
            "avg_chunk_size": round(avg_size, 1),
            "min_chunk_size": min(tamanhos) if tamanhos else 0,
            "max_chunk_size": max(tamanhos) if tamanhos else 0,
            "embedding_dimension": len(chunks_json[0]["embedding"]) if chunks_json else 0,
        })

        print(f"  [{nome_doc}] teste {test_id:02d} ({cfg['strategy']}): {num_chunks} chunks")

    return resultados_resumo

In [ ]:
TESTES = [
    {"test_id": 1,  "strategy": "fixed",              "chunk_size": 200,  "chunk_overlap": 0},
    {"test_id": 2,  "strategy": "fixed",              "chunk_size": 500,  "chunk_overlap": 0},
    {"test_id": 3,  "strategy": "fixed",              "chunk_size": 1000, "chunk_overlap": 0},
    {"test_id": 4,  "strategy": "fixed",              "chunk_size": 2000, "chunk_overlap": 0},
    {"test_id": 5,  "strategy": "fixed_with_overlap", "chunk_size": 500,  "chunk_overlap": 50},
    {"test_id": 6,  "strategy": "fixed_with_overlap", "chunk_size": 500,  "chunk_overlap": 200},
    {"test_id": 7,  "strategy": "by_paragraph",        "chunk_size": None, "chunk_overlap": 0},
    {"test_id": 8,  "strategy": "by_sentence_group3",  "chunk_size": None, "chunk_overlap": 0},
    {"test_id": 9,  "strategy": "recursive",           "chunk_size": 1000, "chunk_overlap": 100},
    {"test_id": 10, "strategy": "markdown_headers",    "chunk_size": None, "chunk_overlap": 0},
]

In [27]:
import json

def processar_documento(nome_doc: str, texto_md: str, pasta_resultados: str):
    resultados_resumo = []   # para o summary.json

    for cfg in TESTES:
        test_id = cfg["test_id"]

        if test_id in [1, 2, 3, 4]:
            textos = gerar_chunks_teste_1_a_4(texto_md, cfg["chunk_size"])
            metadatas = [{} for _ in textos]
        elif test_id in [5, 6]:
            textos = gerar_chunks_teste_5_e_6(texto_md, cfg["chunk_overlap"])
            metadatas = [{} for _ in textos]
        elif test_id == 7:
            textos = gerar_chunks_teste_7(texto_md)
            metadatas = [{} for _ in textos]
        elif test_id == 8:
            textos = gerar_chunks_teste_8(texto_md)
            metadatas = [{} for _ in textos]
        elif test_id == 9:
            textos = gerar_chunks_teste_9(texto_md)
            metadatas = [{} for _ in textos]
        elif test_id == 10:
            docs = gerar_chunks_teste_10(texto_md)
            textos = [d.page_content for d in docs]
            metadatas = [d.metadata for d in docs]

        chunks_json = []
        tamanhos = []
        for i, (texto_chunk, meta) in enumerate(zip(textos, metadatas), start=1):
            if not texto_chunk.strip():
                continue
            emb = gerar_embedding(texto_chunk)
            chunk_id = f"{nome_doc}_test{test_id:02d}_chunk{i:03d}"
            chunk_dict = montar_chunk_dict(
                chunk_id=chunk_id,
                document_id=nome_doc,
                document_name=f"{nome_doc}.pdf",
                test_id=test_id,
                strategy=cfg["strategy"],
                chunk_size=cfg["chunk_size"],
                chunk_overlap=cfg["chunk_overlap"],
                texto=texto_chunk,
                embedding=emb,
                metadata_extra=meta,
            )
            chunks_json.append(chunk_dict)
            tamanhos.append(len(texto_chunk))

        pasta_teste = os.path.join(pasta_resultados, nome_doc, f"test_{test_id:02d}")
        os.makedirs(pasta_teste, exist_ok=True)
        with open(os.path.join(pasta_teste, "chunks_embeddings.json"), "w", encoding="utf-8") as f:
            json.dump(chunks_json, f, ensure_ascii=False, indent=2)

        num_chunks = len(chunks_json)
        avg_size = sum(tamanhos) / num_chunks if num_chunks else 0
        resultados_resumo.append({
            "test_id": test_id,
            "strategy": cfg["strategy"],
            "chunk_size": cfg["chunk_size"],
            "chunk_overlap": cfg["chunk_overlap"],
            "num_chunks": num_chunks,
            "avg_chunk_size": round(avg_size, 1),
            "min_chunk_size": min(tamanhos) if tamanhos else 0,
            "max_chunk_size": max(tamanhos) if tamanhos else 0,
            "embedding_dimension": len(chunks_json[0]["embedding"]) if chunks_json else 0,
        })

        print(f"  [{nome_doc}] teste {test_id:02d} ({cfg['strategy']}): {num_chunks} chunks")

    return resultados_resumo

In [28]:
docs_para_teste_rapido = ["bioetica_e_ia", "escrita_academica_ia", "twitter_algoritmo"]

summary_geral = {}
for nome_doc in docs_para_teste_rapido:
    texto_md = markdowns[nome_doc]
    resumo = processar_documento(nome_doc, texto_md, PASTA_RESULTADOS)
    summary_geral[nome_doc] = resumo

  [bioetica_e_ia] teste 01 (fixed): 269 chunks
  [bioetica_e_ia] teste 02 (fixed): 108 chunks
  [bioetica_e_ia] teste 03 (fixed): 54 chunks
  [bioetica_e_ia] teste 04 (fixed): 27 chunks
  [bioetica_e_ia] teste 05 (fixed_with_overlap): 120 chunks
  [bioetica_e_ia] teste 06 (fixed_with_overlap): 179 chunks
  [bioetica_e_ia] teste 07 (by_paragraph): 1 chunks
  [bioetica_e_ia] teste 08 (by_sentence_group3): 142 chunks
  [bioetica_e_ia] teste 09 (recursive): 73 chunks
  [bioetica_e_ia] teste 10 (markdown_headers): 19 chunks
  [escrita_academica_ia] teste 01 (fixed): 235 chunks
  [escrita_academica_ia] teste 02 (fixed): 94 chunks
  [escrita_academica_ia] teste 03 (fixed): 47 chunks
  [escrita_academica_ia] teste 04 (fixed): 24 chunks
  [escrita_academica_ia] teste 05 (fixed_with_overlap): 105 chunks
  [escrita_academica_ia] teste 06 (fixed_with_overlap): 156 chunks
  [escrita_academica_ia] teste 07 (by_paragraph): 1 chunks
  [escrita_academica_ia] teste 08 (by_sentence_group3): 92 chunks
  [escrita_academica_ia] teste 09 (recursive): 73 chunks
  [escrita_academica_ia] teste 10 (markdown_headers): 20 chunks
  [twitter_algoritmo] teste 01 (fixed): 295 chunks
  [twitter_algoritmo] teste 02 (fixed): 118 chunks
  [twitter_algoritmo] teste 03 (fixed): 59 chunks
  [twitter_algoritmo] teste 04 (fixed): 30 chunks
  [twitter_algoritmo] teste 05 (fixed_with_overlap): 131 chunks
  [twitter_algoritmo] teste 06 (fixed_with_overlap): 196 chunks
  [twitter_algoritmo] teste 07 (by_paragraph): 1 chunks
  [twitter_algoritmo] teste 08 (by_sentence_group3): 122 chunks
  [twitter_algoritmo] teste 09 (recursive): 80 chunks
  [twitter_algoritmo] teste 10 (markdown_headers): 19 chunks

In [29]:
docs_restantes = [d for d in markdowns.keys() if d not in docs_para_teste_rapido]
for nome_doc in docs_restantes:
    texto_md = markdowns[nome_doc]
    resumo = processar_documento(nome_doc, texto_md, PASTA_RESULTADOS)
    summary_geral[nome_doc] = resumo

  [attention_is_all_you_need] teste 01 (fixed): 212 chunks
  [attention_is_all_you_need] teste 02 (fixed): 85 chunks
  [attention_is_all_you_need] teste 03 (fixed): 43 chunks
  [attention_is_all_you_need] teste 04 (fixed): 22 chunks
  [attention_is_all_you_need] teste 05 (fixed_with_overlap): 94 chunks
  [attention_is_all_you_need] teste 06 (fixed_with_overlap): 141 chunks
  [attention_is_all_you_need] teste 07 (by_paragraph): 1 chunks
  [attention_is_all_you_need] teste 08 (by_sentence_group3): 119 chunks
  [attention_is_all_you_need] teste 09 (recursive): 53 chunks
  [attention_is_all_you_need] teste 10 (markdown_headers): 26 chunks
  [bert_pretraining] teste 01 (fixed): 332 chunks
  [bert_pretraining] teste 02 (fixed): 133 chunks
  [bert_pretraining] teste 03 (fixed): 67 chunks
  [bert_pretraining] teste 04 (fixed): 34 chunks
  [bert_pretraining] teste 05 (fixed_with_overlap): 148 chunks
  [bert_pretraining] teste 06 (fixed_with_overlap): 221 chunks
  [bert_pretraining] teste 07 (by_paragraph): 1 chunks
  [bert_pretraining] teste 08 (by_sentence_group3): 193 chunks
  [bert_pretraining] teste 09 (recursive): 86 chunks
  [bert_pretraining] teste 10 (markdown_headers): 31 chunks
  [gpt3_language_models] teste 01 (fixed): 1318 chunks
  [gpt3_language_models] teste 02 (fixed): 527 chunks
  [gpt3_language_models] teste 03 (fixed): 264 chunks
  [gpt3_language_models] teste 04 (fixed): 132 chunks
  [gpt3_language_models] teste 05 (fixed_with_overlap): 586 chunks
  [gpt3_language_models] teste 06 (fixed_with_overlap): 878 chunks

WARNING:langchain_text_splitters.base:Created a chunk of size 6038, which is longer than the specified 4000

  [gpt3_language_models] teste 07 (by_paragraph): 3 chunks
  [gpt3_language_models] teste 08 (by_sentence_group3): 779 chunks
  [gpt3_language_models] teste 09 (recursive): 365 chunks
  [gpt3_language_models] teste 10 (markdown_headers): 63 chunks
  [gpt4_technical_report] teste 01 (fixed): 1476 chunks
  [gpt4_technical_report] teste 02 (fixed): 591 chunks
  [gpt4_technical_report] teste 03 (fixed): 296 chunks
  [gpt4_technical_report] teste 04 (fixed): 148 chunks
  [gpt4_technical_report] teste 05 (fixed_with_overlap): 656 chunks
  [gpt4_technical_report] teste 06 (fixed_with_overlap): 984 chunks

WARNING:langchain_text_splitters.base:Created a chunk of size 18229, which is longer than the specified 4000

  [gpt4_technical_report] teste 07 (by_paragraph): 3 chunks
  [gpt4_technical_report] teste 08 (by_sentence_group3): 628 chunks
  [gpt4_technical_report] teste 09 (recursive): 397 chunks
  [gpt4_technical_report] teste 10 (markdown_headers): 97 chunks
  [instruct_gpt] teste 01 (fixed): 962 chunks
  [instruct_gpt] teste 02 (fixed): 385 chunks
  [instruct_gpt] teste 03 (fixed): 193 chunks
  [instruct_gpt] teste 04 (fixed): 97 chunks
  [instruct_gpt] teste 05 (fixed_with_overlap): 428 chunks
  [instruct_gpt] teste 06 (fixed_with_overlap): 641 chunks
  [instruct_gpt] teste 07 (by_paragraph): 2 chunks
  [instruct_gpt] teste 08 (by_sentence_group3): 468 chunks
  [instruct_gpt] teste 09 (recursive): 259 chunks
  [instruct_gpt] teste 10 (markdown_headers): 54 chunks
  [llama_foundation_models] teste 01 (fixed): 461 chunks
  [llama_foundation_models] teste 02 (fixed): 185 chunks
  [llama_foundation_models] teste 03 (fixed): 93 chunks
  [llama_foundation_models] teste 04 (fixed): 47 chunks
  [llama_foundation_models] teste 05 (fixed_with_overlap): 205 chunks
  [llama_foundation_models] teste 06 (fixed_with_overlap): 307 chunks
  [llama_foundation_models] teste 07 (by_paragraph): 1 chunks
  [llama_foundation_models] teste 08 (by_sentence_group3): 295 chunks
  [llama_foundation_models] teste 09 (recursive): 120 chunks
  [llama_foundation_models] teste 10 (markdown_headers): 51 chunks
  [lora_low_rank_adaptation] teste 01 (fixed): 452 chunks
  [lora_low_rank_adaptation] teste 02 (fixed): 181 chunks
  [lora_low_rank_adaptation] teste 03 (fixed): 91 chunks
  [lora_low_rank_adaptation] teste 04 (fixed): 46 chunks
  [lora_low_rank_adaptation] teste 05 (fixed_with_overlap): 201 chunks
  [lora_low_rank_adaptation] teste 06 (fixed_with_overlap): 301 chunks
  [lora_low_rank_adaptation] teste 07 (by_paragraph): 1 chunks
  [lora_low_rank_adaptation] teste 08 (by_sentence_group3): 249 chunks
  [lora_low_rank_adaptation] teste 09 (recursive): 126 chunks
  [lora_low_rank_adaptation] teste 10 (markdown_headers): 38 chunks
  [retrieval_augmented_generation] teste 01 (fixed): 365 chunks
  [retrieval_augmented_generation] teste 02 (fixed): 146 chunks
  [retrieval_augmented_generation] teste 03 (fixed): 73 chunks
  [retrieval_augmented_generation] teste 04 (fixed): 37 chunks
  [retrieval_augmented_generation] teste 05 (fixed_with_overlap): 162 chunks
  [retrieval_augmented_generation] teste 06 (fixed_with_overlap): 243 chunks
  [retrieval_augmented_generation] teste 07 (by_paragraph): 1 chunks
  [retrieval_augmented_generation] teste 08 (by_sentence_group3): 210 chunks
  [retrieval_augmented_generation] teste 09 (recursive): 100 chunks
  [retrieval_augmented_generation] teste 10 (markdown_headers): 20 chunks
  [scaling_laws_llm] teste 01 (fixed): 478 chunks
  [scaling_laws_llm] teste 02 (fixed): 192 chunks
  [scaling_laws_llm] teste 03 (fixed): 96 chunks
  [scaling_laws_llm] teste 04 (fixed): 48 chunks
  [scaling_laws_llm] teste 05 (fixed_with_overlap): 213 chunks
  [scaling_laws_llm] teste 06 (fixed_with_overlap): 318 chunks
  [scaling_laws_llm] teste 07 (by_paragraph): 1 chunks
  [scaling_laws_llm] teste 08 (by_sentence_group3): 464 chunks
  [scaling_laws_llm] teste 09 (recursive): 122 chunks
  [scaling_laws_llm] teste 10 (markdown_headers): 19 chunks

In [30]:
summary_final = []
for nome_doc, experimentos in summary_geral.items():
    summary_final.append({
        "document": f"{nome_doc}.pdf",
        "experiments": experimentos,
    })

with open(os.path.join(PASTA_RESULTADOS, "summary.json"), "w", encoding="utf-8") as f:
    json.dump(summary_final, f, ensure_ascii=False, indent=2)

print("summary.json gerado com sucesso!")

summary.json gerado com sucesso!

In [31]:
!find /content/drive/MyDrive/Residencia_RAG/results -maxdepth 3 | sort

/content/drive/MyDrive/Residencia_RAG/results
/content/drive/MyDrive/Residencia_RAG/results/attention_is_all_you_need
/content/drive/MyDrive/Residencia_RAG/results/attention_is_all_you_need/markdown
/content/drive/MyDrive/Residencia_RAG/results/attention_is_all_you_need/markdown/attention_is_all_you_need.md
/content/drive/MyDrive/Residencia_RAG/results/attention_is_all_you_need/test_01
/content/drive/MyDrive/Residencia_RAG/results/attention_is_all_you_need/test_01/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/attention_is_all_you_need/test_02
/content/drive/MyDrive/Residencia_RAG/results/attention_is_all_you_need/test_02/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/attention_is_all_you_need/test_03
/content/drive/MyDrive/Residencia_RAG/results/attention_is_all_you_need/test_03/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/attention_is_all_you_need/test_04
/content/drive/MyDrive/Residencia_RAG/results/attention_is_all_you_need/test_04/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/attention_is_all_you_need/test_05
/content/drive/MyDrive/Residencia_RAG/results/attention_is_all_you_need/test_05/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/attention_is_all_you_need/test_06
/content/drive/MyDrive/Residencia_RAG/results/attention_is_all_you_need/test_06/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/attention_is_all_you_need/test_07
/content/drive/MyDrive/Residencia_RAG/results/attention_is_all_you_need/test_07/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/attention_is_all_you_need/test_08
/content/drive/MyDrive/Residencia_RAG/results/attention_is_all_you_need/test_08/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/attention_is_all_you_need/test_09
/content/drive/MyDrive/Residencia_RAG/results/attention_is_all_you_need/test_09/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/attention_is_all_you_need/test_10
/content/drive/MyDrive/Residencia_RAG/results/attention_is_all_you_need/test_10/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/bert_pretraining
/content/drive/MyDrive/Residencia_RAG/results/bert_pretraining/markdown
/content/drive/MyDrive/Residencia_RAG/results/bert_pretraining/markdown/bert_pretraining.md
/content/drive/MyDrive/Residencia_RAG/results/bert_pretraining/test_01
/content/drive/MyDrive/Residencia_RAG/results/bert_pretraining/test_01/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/bert_pretraining/test_02
/content/drive/MyDrive/Residencia_RAG/results/bert_pretraining/test_02/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/bert_pretraining/test_03
/content/drive/MyDrive/Residencia_RAG/results/bert_pretraining/test_03/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/bert_pretraining/test_04
/content/drive/MyDrive/Residencia_RAG/results/bert_pretraining/test_04/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/bert_pretraining/test_05
/content/drive/MyDrive/Residencia_RAG/results/bert_pretraining/test_05/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/bert_pretraining/test_06
/content/drive/MyDrive/Residencia_RAG/results/bert_pretraining/test_06/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/bert_pretraining/test_07
/content/drive/MyDrive/Residencia_RAG/results/bert_pretraining/test_07/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/bert_pretraining/test_08
/content/drive/MyDrive/Residencia_RAG/results/bert_pretraining/test_08/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/bert_pretraining/test_09
/content/drive/MyDrive/Residencia_RAG/results/bert_pretraining/test_09/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/bert_pretraining/test_10
/content/drive/MyDrive/Residencia_RAG/results/bert_pretraining/test_10/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/bioetica_e_ia
/content/drive/MyDrive/Residencia_RAG/results/bioetica_e_ia/markdown
/content/drive/MyDrive/Residencia_RAG/results/bioetica_e_ia/markdown/bioetica_e_ia.md
/content/drive/MyDrive/Residencia_RAG/results/bioetica_e_ia/test_01
/content/drive/MyDrive/Residencia_RAG/results/bioetica_e_ia/test_01/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/bioetica_e_ia/test_02
/content/drive/MyDrive/Residencia_RAG/results/bioetica_e_ia/test_02/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/bioetica_e_ia/test_03
/content/drive/MyDrive/Residencia_RAG/results/bioetica_e_ia/test_03/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/bioetica_e_ia/test_04
/content/drive/MyDrive/Residencia_RAG/results/bioetica_e_ia/test_04/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/bioetica_e_ia/test_05
/content/drive/MyDrive/Residencia_RAG/results/bioetica_e_ia/test_05/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/bioetica_e_ia/test_06
/content/drive/MyDrive/Residencia_RAG/results/bioetica_e_ia/test_06/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/bioetica_e_ia/test_07
/content/drive/MyDrive/Residencia_RAG/results/bioetica_e_ia/test_07/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/bioetica_e_ia/test_08
/content/drive/MyDrive/Residencia_RAG/results/bioetica_e_ia/test_08/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/bioetica_e_ia/test_09
/content/drive/MyDrive/Residencia_RAG/results/bioetica_e_ia/test_09/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/bioetica_e_ia/test_10
/content/drive/MyDrive/Residencia_RAG/results/bioetica_e_ia/test_10/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/escrita_academica_ia
/content/drive/MyDrive/Residencia_RAG/results/escrita_academica_ia/markdown
/content/drive/MyDrive/Residencia_RAG/results/escrita_academica_ia/markdown/escrita_academica_ia.md
/content/drive/MyDrive/Residencia_RAG/results/escrita_academica_ia/test_01
/content/drive/MyDrive/Residencia_RAG/results/escrita_academica_ia/test_01/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/escrita_academica_ia/test_02
/content/drive/MyDrive/Residencia_RAG/results/escrita_academica_ia/test_02/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/escrita_academica_ia/test_03
/content/drive/MyDrive/Residencia_RAG/results/escrita_academica_ia/test_03/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/escrita_academica_ia/test_04
/content/drive/MyDrive/Residencia_RAG/results/escrita_academica_ia/test_04/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/escrita_academica_ia/test_05
/content/drive/MyDrive/Residencia_RAG/results/escrita_academica_ia/test_05/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/escrita_academica_ia/test_06
/content/drive/MyDrive/Residencia_RAG/results/escrita_academica_ia/test_06/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/escrita_academica_ia/test_07
/content/drive/MyDrive/Residencia_RAG/results/escrita_academica_ia/test_07/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/escrita_academica_ia/test_08
/content/drive/MyDrive/Residencia_RAG/results/escrita_academica_ia/test_08/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/escrita_academica_ia/test_09
/content/drive/MyDrive/Residencia_RAG/results/escrita_academica_ia/test_09/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/escrita_academica_ia/test_10
/content/drive/MyDrive/Residencia_RAG/results/escrita_academica_ia/test_10/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/gpt3_language_models
/content/drive/MyDrive/Residencia_RAG/results/gpt3_language_models/markdown
/content/drive/MyDrive/Residencia_RAG/results/gpt3_language_models/markdown/gpt3_language_models.md
/content/drive/MyDrive/Residencia_RAG/results/gpt3_language_models/test_01
/content/drive/MyDrive/Residencia_RAG/results/gpt3_language_models/test_01/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/gpt3_language_models/test_02
/content/drive/MyDrive/Residencia_RAG/results/gpt3_language_models/test_02/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/gpt3_language_models/test_03
/content/drive/MyDrive/Residencia_RAG/results/gpt3_language_models/test_03/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/gpt3_language_models/test_04
/content/drive/MyDrive/Residencia_RAG/results/gpt3_language_models/test_04/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/gpt3_language_models/test_05
/content/drive/MyDrive/Residencia_RAG/results/gpt3_language_models/test_05/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/gpt3_language_models/test_06
/content/drive/MyDrive/Residencia_RAG/results/gpt3_language_models/test_06/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/gpt3_language_models/test_07
/content/drive/MyDrive/Residencia_RAG/results/gpt3_language_models/test_07/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/gpt3_language_models/test_08
/content/drive/MyDrive/Residencia_RAG/results/gpt3_language_models/test_08/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/gpt3_language_models/test_09
/content/drive/MyDrive/Residencia_RAG/results/gpt3_language_models/test_09/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/gpt3_language_models/test_10
/content/drive/MyDrive/Residencia_RAG/results/gpt3_language_models/test_10/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/gpt4_technical_report
/content/drive/MyDrive/Residencia_RAG/results/gpt4_technical_report/markdown
/content/drive/MyDrive/Residencia_RAG/results/gpt4_technical_report/markdown/gpt4_technical_report.md
/content/drive/MyDrive/Residencia_RAG/results/gpt4_technical_report/test_01
/content/drive/MyDrive/Residencia_RAG/results/gpt4_technical_report/test_01/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/gpt4_technical_report/test_02
/content/drive/MyDrive/Residencia_RAG/results/gpt4_technical_report/test_02/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/gpt4_technical_report/test_03
/content/drive/MyDrive/Residencia_RAG/results/gpt4_technical_report/test_03/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/gpt4_technical_report/test_04
/content/drive/MyDrive/Residencia_RAG/results/gpt4_technical_report/test_04/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/gpt4_technical_report/test_05
/content/drive/MyDrive/Residencia_RAG/results/gpt4_technical_report/test_05/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/gpt4_technical_report/test_06
/content/drive/MyDrive/Residencia_RAG/results/gpt4_technical_report/test_06/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/gpt4_technical_report/test_07
/content/drive/MyDrive/Residencia_RAG/results/gpt4_technical_report/test_07/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/gpt4_technical_report/test_08
/content/drive/MyDrive/Residencia_RAG/results/gpt4_technical_report/test_08/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/gpt4_technical_report/test_09
/content/drive/MyDrive/Residencia_RAG/results/gpt4_technical_report/test_09/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/gpt4_technical_report/test_10
/content/drive/MyDrive/Residencia_RAG/results/gpt4_technical_report/test_10/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/instruct_gpt
/content/drive/MyDrive/Residencia_RAG/results/instruct_gpt/markdown
/content/drive/MyDrive/Residencia_RAG/results/instruct_gpt/markdown/instruct_gpt.md
/content/drive/MyDrive/Residencia_RAG/results/instruct_gpt/test_01
/content/drive/MyDrive/Residencia_RAG/results/instruct_gpt/test_01/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/instruct_gpt/test_02
/content/drive/MyDrive/Residencia_RAG/results/instruct_gpt/test_02/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/instruct_gpt/test_03
/content/drive/MyDrive/Residencia_RAG/results/instruct_gpt/test_03/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/instruct_gpt/test_04
/content/drive/MyDrive/Residencia_RAG/results/instruct_gpt/test_04/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/instruct_gpt/test_05
/content/drive/MyDrive/Residencia_RAG/results/instruct_gpt/test_05/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/instruct_gpt/test_06
/content/drive/MyDrive/Residencia_RAG/results/instruct_gpt/test_06/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/instruct_gpt/test_07
/content/drive/MyDrive/Residencia_RAG/results/instruct_gpt/test_07/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/instruct_gpt/test_08
/content/drive/MyDrive/Residencia_RAG/results/instruct_gpt/test_08/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/instruct_gpt/test_09
/content/drive/MyDrive/Residencia_RAG/results/instruct_gpt/test_09/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/instruct_gpt/test_10
/content/drive/MyDrive/Residencia_RAG/results/instruct_gpt/test_10/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/llama_foundation_models
/content/drive/MyDrive/Residencia_RAG/results/llama_foundation_models/markdown
/content/drive/MyDrive/Residencia_RAG/results/llama_foundation_models/markdown/llama_foundation_models.md
/content/drive/MyDrive/Residencia_RAG/results/llama_foundation_models/test_01
/content/drive/MyDrive/Residencia_RAG/results/llama_foundation_models/test_01/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/llama_foundation_models/test_02
/content/drive/MyDrive/Residencia_RAG/results/llama_foundation_models/test_02/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/llama_foundation_models/test_03
/content/drive/MyDrive/Residencia_RAG/results/llama_foundation_models/test_03/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/llama_foundation_models/test_04
/content/drive/MyDrive/Residencia_RAG/results/llama_foundation_models/test_04/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/llama_foundation_models/test_05
/content/drive/MyDrive/Residencia_RAG/results/llama_foundation_models/test_05/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/llama_foundation_models/test_06
/content/drive/MyDrive/Residencia_RAG/results/llama_foundation_models/test_06/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/llama_foundation_models/test_07
/content/drive/MyDrive/Residencia_RAG/results/llama_foundation_models/test_07/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/llama_foundation_models/test_08
/content/drive/MyDrive/Residencia_RAG/results/llama_foundation_models/test_08/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/llama_foundation_models/test_09
/content/drive/MyDrive/Residencia_RAG/results/llama_foundation_models/test_09/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/llama_foundation_models/test_10
/content/drive/MyDrive/Residencia_RAG/results/llama_foundation_models/test_10/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/lora_low_rank_adaptation
/content/drive/MyDrive/Residencia_RAG/results/lora_low_rank_adaptation/markdown
/content/drive/MyDrive/Residencia_RAG/results/lora_low_rank_adaptation/markdown/lora_low_rank_adaptation.md
/content/drive/MyDrive/Residencia_RAG/results/lora_low_rank_adaptation/test_01
/content/drive/MyDrive/Residencia_RAG/results/lora_low_rank_adaptation/test_01/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/lora_low_rank_adaptation/test_02
/content/drive/MyDrive/Residencia_RAG/results/lora_low_rank_adaptation/test_02/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/lora_low_rank_adaptation/test_03
/content/drive/MyDrive/Residencia_RAG/results/lora_low_rank_adaptation/test_03/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/lora_low_rank_adaptation/test_04
/content/drive/MyDrive/Residencia_RAG/results/lora_low_rank_adaptation/test_04/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/lora_low_rank_adaptation/test_05
/content/drive/MyDrive/Residencia_RAG/results/lora_low_rank_adaptation/test_05/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/lora_low_rank_adaptation/test_06
/content/drive/MyDrive/Residencia_RAG/results/lora_low_rank_adaptation/test_06/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/lora_low_rank_adaptation/test_07
/content/drive/MyDrive/Residencia_RAG/results/lora_low_rank_adaptation/test_07/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/lora_low_rank_adaptation/test_08
/content/drive/MyDrive/Residencia_RAG/results/lora_low_rank_adaptation/test_08/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/lora_low_rank_adaptation/test_09
/content/drive/MyDrive/Residencia_RAG/results/lora_low_rank_adaptation/test_09/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/lora_low_rank_adaptation/test_10
/content/drive/MyDrive/Residencia_RAG/results/lora_low_rank_adaptation/test_10/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/retrieval_augmented_generation
/content/drive/MyDrive/Residencia_RAG/results/retrieval_augmented_generation/markdown
/content/drive/MyDrive/Residencia_RAG/results/retrieval_augmented_generation/markdown/retrieval_augmented_generation.md
/content/drive/MyDrive/Residencia_RAG/results/retrieval_augmented_generation/test_01
/content/drive/MyDrive/Residencia_RAG/results/retrieval_augmented_generation/test_01/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/retrieval_augmented_generation/test_02
/content/drive/MyDrive/Residencia_RAG/results/retrieval_augmented_generation/test_02/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/retrieval_augmented_generation/test_03
/content/drive/MyDrive/Residencia_RAG/results/retrieval_augmented_generation/test_03/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/retrieval_augmented_generation/test_04
/content/drive/MyDrive/Residencia_RAG/results/retrieval_augmented_generation/test_04/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/retrieval_augmented_generation/test_05
/content/drive/MyDrive/Residencia_RAG/results/retrieval_augmented_generation/test_05/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/retrieval_augmented_generation/test_06
/content/drive/MyDrive/Residencia_RAG/results/retrieval_augmented_generation/test_06/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/retrieval_augmented_generation/test_07
/content/drive/MyDrive/Residencia_RAG/results/retrieval_augmented_generation/test_07/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/retrieval_augmented_generation/test_08
/content/drive/MyDrive/Residencia_RAG/results/retrieval_augmented_generation/test_08/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/retrieval_augmented_generation/test_09
/content/drive/MyDrive/Residencia_RAG/results/retrieval_augmented_generation/test_09/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/retrieval_augmented_generation/test_10
/content/drive/MyDrive/Residencia_RAG/results/retrieval_augmented_generation/test_10/chunks_embeddings.json
/content/drive/MyDrive/Residencia_RAG/results/scaling_laws_llm

In [32]:
import pandas as pd

linhas = []
for nome_doc, experimentos in summary_geral.items():
    for exp in experimentos:
        if exp["test_id"] in [1, 2, 3, 4, 5, 6]:
            pct_overlap = 0
            if exp["chunk_size"]:
                pct_overlap = round((exp["chunk_overlap"] / exp["chunk_size"]) * 100, 1)
            linhas.append({
                "documento": nome_doc,
                "teste": exp["test_id"],
                "chunk_size": exp["chunk_size"],
                "chunk_overlap": exp["chunk_overlap"],
                "percentual_overlap": pct_overlap,
                "num_chunks": exp["num_chunks"],
                "tamanho_medio": exp["avg_chunk_size"],
            })

df_stats = pd.DataFrame(linhas)
df_stats

,documento,teste,chunk_size,chunk_overlap,percentual_overlap,num_chunks,tamanho_medio
0,bioetica_e_ia,1,200,0,0.0,269,199.0
1,bioetica_e_ia,2,500,0,0.0,108,496.2
2,bioetica_e_ia,3,1000,0,0.0,54,992.7
3,bioetica_e_ia,4,2000,0,0.0,27,1985.6
4,bioetica_e_ia,5,500,50,10.0,120,496.1
...,...,...,...,...,...,...,...
67,scaling_laws_llm,2,500,0,0.0,192,497.1
68,scaling_laws_llm,3,1000,0,0.0,96,994.6
69,scaling_laws_llm,4,2000,0,0.0,48,1989.6
70,scaling_laws_llm,5,500,50,10.0,213,497.8
71,scaling_laws_llm,6,500,200,40.0,318,499.3

In [33]:
with open(os.path.join(PASTA_RESULTADOS, "bioetica_e_ia", "test_03", "chunks_embeddings.json"),
          encoding="utf-8") as f:
    exemplo_chunks = json.load(f)

for c in exemplo_chunks[:3]:
    print(c["chunk_id"], "-> caracteres:", len(c["text"]), "| tokens:", contar_tokens(c["text"]))

bioetica_e_ia_test03_chunk001 -> caracteres: 1000 | tokens: 286
bioetica_e_ia_test03_chunk002 -> caracteres: 1000 | tokens: 248
bioetica_e_ia_test03_chunk003 -> caracteres: 1000 | tokens: 241

In [34]:
import json

print("="*70)
print("RESUMO GERAL (do summary.json)")
print("="*70)

with open(f"{PASTA_RESULTADOS}/summary.json", encoding="utf-8") as f:
    summary = json.load(f)

for doc in summary:
    print(f"\n--- {doc['document']} ---")
    for exp in doc["experiments"]:
        print(f"  Teste {exp['test_id']:02d} ({exp['strategy']:<20}) "
              f"-> {exp['num_chunks']:>5} chunks | "
              f"tam. médio: {exp['avg_chunk_size']:>7} | "
              f"min: {exp['min_chunk_size']:>5} | max: {exp['max_chunk_size']:>5}")

======================================================================
RESUMO GERAL (do summary.json)
======================================================================

--- bioetica_e_ia.pdf ---
  Teste 01 (fixed               ) ->   269 chunks | tam. médio:   199.0 | min:    17 | max:   200
  Teste 02 (fixed               ) ->   108 chunks | tam. médio:   496.2 | min:   117 | max:   500
  Teste 03 (fixed               ) ->    54 chunks | tam. médio:   992.7 | min:   617 | max:  1000
  Teste 04 (fixed               ) ->    27 chunks | tam. médio:  1985.6 | min:  1617 | max:  2000
  Teste 05 (fixed_with_overlap  ) ->   120 chunks | tam. médio:   496.1 | min:    67 | max:   500
  Teste 06 (fixed_with_overlap  ) ->   179 chunks | tam. médio:   498.1 | min:   216 | max:   500
  Teste 07 (by_paragraph        ) ->     1 chunks | tam. médio: 53617.0 | min: 53617 | max: 53617
  Teste 08 (by_sentence_group3  ) ->   142 chunks | tam. médio:   375.6 | min:    36 | max:  1133
  Teste 09 (recursive           ) ->    73 chunks | tam. médio:   755.5 | min:    16 | max:   998
  Teste 10 (markdown_headers    ) ->    19 chunks | tam. médio:  2770.7 | min:   115 | max:  8779

--- escrita_academica_ia.pdf ---
  Teste 01 (fixed               ) ->   235 chunks | tam. médio:   199.1 | min:    82 | max:   200
  Teste 02 (fixed               ) ->    94 chunks | tam. médio:   498.4 | min:   382 | max:   500
  Teste 03 (fixed               ) ->    47 chunks | tam. médio:   997.0 | min:   881 | max:  1000
  Teste 04 (fixed               ) ->    24 chunks | tam. médio:  1953.0 | min:   881 | max:  2000
  Teste 05 (fixed_with_overlap  ) ->   105 chunks | tam. médio:   495.6 | min:    82 | max:   500
  Teste 06 (fixed_with_overlap  ) ->   156 chunks | tam. médio:   498.9 | min:   382 | max:   500
  Teste 07 (by_paragraph        ) ->     1 chunks | tam. médio: 46866.0 | min: 46866 | max: 46866
  Teste 08 (by_sentence_group3  ) ->    92 chunks | tam. médio:   507.2 | min:    88 | max:  1490
  Teste 09 (recursive           ) ->    73 chunks | tam. médio:   661.8 | min:    30 | max:   999
  Teste 10 (markdown_headers    ) ->    20 chunks | tam. médio:  2294.8 | min:    28 | max:  6749

--- twitter_algoritmo.pdf ---
  Teste 01 (fixed               ) ->   295 chunks | tam. médio:   199.6 | min:   178 | max:   200
  Teste 02 (fixed               ) ->   118 chunks | tam. médio:   499.5 | min:   478 | max:   500
  Teste 03 (fixed               ) ->    59 chunks | tam. médio:   999.4 | min:   978 | max:  1000
  Teste 04 (fixed               ) ->    30 chunks | tam. médio:  1965.7 | min:   978 | max:  2000
  Teste 05 (fixed_with_overlap  ) ->   131 chunks | tam. médio:   499.4 | min:   478 | max:   500
  Teste 06 (fixed_with_overlap  ) ->   196 chunks | tam. médio:   499.5 | min:   478 | max:   500
  Teste 07 (by_paragraph        ) ->     1 chunks | tam. médio: 58924.0 | min: 58924 | max: 58924
  Teste 08 (by_sentence_group3  ) ->   122 chunks | tam. médio:   480.4 | min:    37 | max:  2192
  Teste 09 (recursive           ) ->    80 chunks | tam. médio:   750.0 | min:   147 | max:   997
  Teste 10 (markdown_headers    ) ->    19 chunks | tam. médio:  3052.5 | min:   144 | max: 10064

--- attention_is_all_you_need.pdf ---
  Teste 01 (fixed               ) ->   212 chunks | tam. médio:   199.1 | min:   104 | max:   200
  Teste 02 (fixed               ) ->    85 chunks | tam. médio:   497.4 | min:   304 | max:   500
  Teste 03 (fixed               ) ->    43 chunks | tam. médio:   983.5 | min:   304 | max:  1000
  Teste 04 (fixed               ) ->    22 chunks | tam. médio:  1922.6 | min:   304 | max:  2000
  Teste 05 (fixed_with_overlap  ) ->    94 chunks | tam. médio:   499.2 | min:   454 | max:   500
  Teste 06 (fixed_with_overlap  ) ->   141 chunks | tam. médio:   498.2 | min:   304 | max:   500
  Teste 07 (by_paragraph        ) ->     1 chunks | tam. médio: 42274.0 | min: 42274 | max: 42274
  Teste 08 (by_sentence_group3  ) ->   119 chunks | tam. médio:   352.6 | min:    62 | max:  1329
  Teste 09 (recursive           ) ->    53 chunks | tam. médio:   809.5 | min:   242 | max:   995
  Teste 10 (markdown_headers    ) ->    26 chunks | tam. médio:  1590.8 | min:    58 | max:  8519

--- bert_pretraining.pdf ---
  Teste 01 (fixed               ) ->   332 chunks | tam. médio:   199.5 | min:   131 | max:   200
  Teste 02 (fixed               ) ->   133 chunks | tam. médio:   498.4 | min:   331 | max:   500
  Teste 03 (fixed               ) ->    67 chunks | tam. médio:   989.7 | min:   331 | max:  1000
  Teste 04 (fixed               ) ->    34 chunks | tam. médio:  1950.8 | min:   331 | max:  2000
  Teste 05 (fixed_with_overlap  ) ->   148 chunks | tam. médio:   497.4 | min:   181 | max:   500
  Teste 06 (fixed_with_overlap  ) ->   221 chunks | tam. médio:   498.9 | min:   331 | max:   500
  Teste 07 (by_paragraph        ) ->     1 chunks | tam. médio: 66305.0 | min: 66305 | max: 66305
  Teste 08 (by_sentence_group3  ) ->   193 chunks | tam. médio:   340.9 | min:    32 | max:  1208
  Teste 09 (recursive           ) ->    86 chunks | tam. médio:   782.4 | min:   136 | max:   997
  Teste 10 (markdown_headers    ) ->    31 chunks | tam. médio:  2090.3 | min:    69 | max: 11550

--- gpt3_language_models.pdf ---
  Teste 01 (fixed               ) ->  1318 chunks | tam. médio:   199.5 | min:    12 | max:   200
  Teste 02 (fixed               ) ->   527 chunks | tam. médio:   499.5 | min:   412 | max:   500
  Teste 03 (fixed               ) ->   264 chunks | tam. médio:   997.5 | min:   412 | max:  1000
  Teste 04 (fixed               ) ->   132 chunks | tam. médio:  1995.2 | min:  1412 | max:  2000
  Teste 05 (fixed_with_overlap  ) ->   586 chunks | tam. médio:   499.1 | min:   161 | max:   500
  Teste 06 (fixed_with_overlap  ) ->   878 chunks | tam. médio:   499.4 | min:   312 | max:   500
  Teste 07 (by_paragraph        ) ->     3 chunks | tam. médio: 87713.3 | min: 65614 | max: 99035
  Teste 08 (by_sentence_group3  ) ->   779 chunks | tam. médio:   336.0 | min:     5 | max:  6044
  Teste 09 (recursive           ) ->   365 chunks | tam. médio:   737.6 | min:     2 | max:   999
  Teste 10 (markdown_headers    ) ->    63 chunks | tam. médio:  4138.9 | min:   149 | max: 28308

--- gpt4_technical_report.pdf ---
  Teste 01 (fixed               ) ->  1476 chunks | tam. médio:   199.6 | min:   137 | max:   200
  Teste 02 (fixed               ) ->   591 chunks | tam. médio:   499.1 | min:   137 | max:   500
  Teste 03 (fixed               ) ->   296 chunks | tam. médio:   996.8 | min:   137 | max:  1000
  Teste 04 (fixed               ) ->   148 chunks | tam. médio:  1993.9 | min:  1136 | max:  2000
  Teste 05 (fixed_with_overlap  ) ->   656 chunks | tam. médio:   499.5 | min:   386 | max:   500
  Teste 06 (fixed_with_overlap  ) ->   984 chunks | tam. médio:   499.4 | min:   237 | max:   500
  Teste 07 (by_paragraph        ) ->     3 chunks | tam. médio: 98349.7 | min: 95637 | max: 99992
  Teste 08 (by_sentence_group3  ) ->   628 chunks | tam. médio:   467.1 | min:    31 | max: 18703
  Teste 09 (recursive           ) ->   397 chunks | tam. médio:   762.6 | min:     2 | max:   999
  Teste 10 (markdown_headers    ) ->    97 chunks | tam. médio:  2994.3 | min:    35 | max: 22982

--- instruct_gpt.pdf ---
  Teste 01 (fixed               ) ->   962 chunks | tam. médio:   199.5 | min:    58 | max:   200
  Teste 02 (fixed               ) ->   385 chunks | tam. médio:   499.0 | min:   258 | max:   500
  Teste 03 (fixed               ) ->   193 chunks | tam. médio:   995.8 | min:   258 | max:  1000
  Teste 04 (fixed               ) ->    97 chunks | tam. médio:  1981.6 | min:   258 | max:  2000
  Teste 05 (fixed_with_overlap  ) ->   428 chunks | tam. médio:   498.8 | min:   108 | max:   500
  Teste 06 (fixed_with_overlap  ) ->   641 chunks | tam. médio:   499.3 | min:   258 | max:   500
  Teste 07 (by_paragraph        ) ->     2 chunks | tam. médio: 96076.5 | min: 92247 | max: 99906
  Teste 08 (by_sentence_group3  ) ->   468 chunks | tam. médio:   408.0 | min:     2 | max:  3684
  Teste 09 (recursive           ) ->   259 chunks | tam. médio:   759.3 | min:    21 | max:   999
  Teste 10 (markdown_headers    ) ->    54 chunks | tam. médio:  3514.1 | min:   149 | max: 21291

--- llama_foundation_models.pdf ---
  Teste 01 (fixed               ) ->   461 chunks | tam. médio:   199.4 | min:   111 | max:   200
  Teste 02 (fixed               ) ->   185 chunks | tam. médio:   497.5 | min:   111 | max:   500
  Teste 03 (fixed               ) ->    93 chunks | tam. médio:   990.1 | min:   111 | max:  1000
  Teste 04 (fixed               ) ->    47 chunks | tam. médio:  1959.4 | min:   111 | max:  2000
  Teste 05 (fixed_with_overlap  ) ->   205 chunks | tam. médio:   498.6 | min:   311 | max:   500
  Teste 06 (fixed_with_overlap  ) ->   307 chunks | tam. médio:   499.0 | min:   311 | max:   500
  Teste 07 (by_paragraph        ) ->     1 chunks | tam. médio: 92073.0 | min: 92073 | max: 92073
  Teste 08 (by_sentence_group3  ) ->   295 chunks | tam. médio:   309.9 | min:    51 | max:  1846
  Teste 09 (recursive           ) ->   120 chunks | tam. médio:   780.3 | min:   143 | max:   997
  Teste 10 (markdown_headers    ) ->    51 chunks | tam. médio:  1758.4 | min:   145 | max: 21626

--- lora_low_rank_adaptation.pdf ---
  Teste 01 (fixed               ) ->   452 chunks | tam. médio:   199.3 | min:    38 | max:   200
  Teste 02 (fixed               ) ->   181 chunks | tam. médio:   498.3 | min:   238 | max:   500
  Teste 03 (fixed               ) ->    91 chunks | tam. médio:   991.4 | min:   238 | max:  1000
  Teste 04 (fixed               ) ->    46 chunks | tam. médio:  1961.4 | min:   238 | max:  2000
  Teste 05 (fixed_with_overlap  ) ->   201 chunks | tam. médio:   498.4 | min:   238 | max:   500
  Teste 06 (fixed_with_overlap  ) ->   301 chunks | tam. médio:   498.8 | min:   238 | max:   500
  Teste 07 (by_paragraph        ) ->     1 chunks | tam. médio: 90174.0 | min: 90174 | max: 90174
  Teste 08 (by_sentence_group3  ) ->   249 chunks | tam. médio:   359.9 | min:    58 | max:  2289
  Teste 09 (recursive           ) ->   126 chunks | tam. médio:   731.2 | min:   140 | max:   999
  Teste 10 (markdown_headers    ) ->    38 chunks | tam. médio:  2333.6 | min:    87 | max: 13653

--- retrieval_augmented_generation.pdf ---
  Teste 01 (fixed               ) ->   365 chunks | tam. médio:   199.2 | min:    33 | max:   200
  Teste 02 (fixed               ) ->   146 chunks | tam. médio:   498.5 | min:   333 | max:   500
  Teste 03 (fixed               ) ->    73 chunks | tam. médio:   997.3 | min:   833 | max:  1000
  Teste 04 (fixed               ) ->    37 chunks | tam. médio:  1968.2 | min:   833 | max:  2000
  Teste 05 (fixed_with_overlap  ) ->   162 chunks | tam. médio:   499.0 | min:   383 | max:   500
  Teste 06 (fixed_with_overlap  ) ->   243 chunks | tam. médio:   498.6 | min:   233 | max:   500
  Teste 07 (by_paragraph        ) ->     1 chunks | tam. médio: 72809.0 | min: 72809 | max: 72809
  Teste 08 (by_sentence_group3  ) ->   210 chunks | tam. médio:   344.6 | min:    54 | max:  1417
  Teste 09 (recursive           ) ->   100 chunks | tam. médio:   738.1 | min:   120 | max:   997
  Teste 10 (markdown_headers    ) ->    20 chunks | tam. médio:  3602.7 | min:   105 | max: 23641

--- scaling_laws_llm.pdf ---
  Teste 01 (fixed               ) ->   478 chunks | tam. médio:   199.4 | min:   111 | max:   200
  Teste 02 (fixed               ) ->   192 chunks | tam. médio:   497.1 | min:    11 | max:   500
  Teste 03 (fixed               ) ->    96 chunks | tam. médio:   994.6 | min:   511 | max:  1000
  Teste 04 (fixed               ) ->    48 chunks | tam. médio:  1989.6 | min:  1511 | max:  2000
  Teste 05 (fixed_with_overlap  ) ->   213 chunks | tam. médio:   497.8 | min:   111 | max:   500
  Teste 06 (fixed_with_overlap  ) ->   318 chunks | tam. médio:   499.3 | min:   411 | max:   500
  Teste 07 (by_paragraph        ) ->     1 chunks | tam. médio: 95355.0 | min: 95355 | max: 95355
  Teste 08 (by_sentence_group3  ) ->   464 chunks | tam. médio:   204.2 | min:     5 | max:  2367
  Teste 09 (recursive           ) ->   122 chunks | tam. médio:   794.7 | min:    30 | max:   997
  Teste 10 (markdown_headers    ) ->    19 chunks | tam. médio:  4981.6 | min:   241 | max: 13351

In [35]:
from collections import defaultdict

totais_por_teste = defaultdict(int)
for doc in summary:
    for exp in doc["experiments"]:
        totais_por_teste[exp["test_id"]] += exp["num_chunks"]

mais_chunks = max(totais_por_teste, key=totais_por_teste.get)
menos_chunks = min(totais_por_teste, key=totais_por_teste.get)

print("Total de chunks por teste (somando todos os documentos):")
for t in sorted(totais_por_teste):
    print(f"  Teste {t:02d}: {totais_por_teste[t]} chunks")

print(f"\n➡️ Teste que MAIS gerou chunks: Teste {mais_chunks} ({totais_por_teste[mais_chunks]} chunks)")
print(f"➡️ Teste que MENOS gerou chunks: Teste {menos_chunks} ({totais_por_teste[menos_chunks]} chunks)")

Total de chunks por teste (somando todos os documentos):
  Teste 01: 6855 chunks
  Teste 02: 2745 chunks
  Teste 03: 1376 chunks
  Teste 04: 692 chunks
  Teste 05: 3049 chunks
  Teste 06: 4565 chunks
  Teste 07: 17 chunks
  Teste 08: 3761 chunks
  Teste 09: 1854 chunks
  Teste 10: 457 chunks

➡️ Teste que MAIS gerou chunks: Teste 1 (6855 chunks)
➡️ Teste que MENOS gerou chunks: Teste 7 (17 chunks)

In [36]:
# Exemplo: 2 chunks do teste 3 (1000 caracteres) e 2 do teste 10 (markdown/heading)
for test_id in [3, 10]:
    with open(f"{PASTA_RESULTADOS}/bioetica_e_ia/test_{test_id:02d}/chunks_embeddings.json",
              encoding="utf-8") as f:
        chunks = json.load(f)
    print(f"\n===== Exemplos do Teste {test_id} =====")
    for c in chunks[:2]:
        print(f"\nchunk_id: {c['chunk_id']}")
        print(f"metadata: {c['metadata']}")
        print(f"texto (primeiros 300 caracteres): {c['text'][:300]}...")

===== Exemplos do Teste 3 =====

chunk_id: bioetica_e_ia_test03_chunk001
metadata: {}
texto (primeiros 300 caracteres): Revista Bioética

Print version ISSN 1983-8042 | On-line version ISSN 1983-8034

Rev. Bioét. vol.34 Brasília 2026

# **Entre o algoritmo e o Juramento de Hipócrates: bioética na era da inteligência artificial**

_Juracy Barbosa dos Santos_<sup>1</sup> _, Guilhermina Rego_<sup>1</sup> _, Rui Nune...

chunk_id: bioetica_e_ia_test03_chunk002
metadata: {}
texto (primeiros 300 caracteres): ipócrates. A incorporação da inteligência artificial na medicina suscita tensões entre eficiência automatizada e valores humanos. Este artigo revisa a literatura sobre os principais dilemas éticos da aplicação da inteligência artificial na prática médica e avalia em que medida os princípios hipocrát...

===== Exemplos do Teste 10 =====

chunk_id: bioetica_e_ia_test10_chunk001
metadata: {}
texto (primeiros 300 caracteres): Revista Bioética
Print version ISSN 1983-8042 | On-line version ISSN 1983-8034
Rev. Bioét. vol.34 Brasília 2026...

chunk_id: bioetica_e_ia_test10_chunk002
metadata: {'heading_1': '**Entre o algoritmo e o Juramento de Hipócrates: bioética na era da inteligência artificial**'}
texto (primeiros 300 caracteres): _Juracy Barbosa dos Santos_<sup>1</sup> _, Guilhermina Rego_<sup>1</sup> _, Rui Nunes_<sup>1</sup>
**1.** Faculdade de Medicina da Universidade do Porto, Porto, Portugal....

In [39]:
import json
from collections import defaultdict

print("="*70)
print("RESUMO GERAL (do summary.json)")
print("="*70)

with open(f"{PASTA_RESULTADOS}/summary.json", encoding="utf-8") as f:
    summary = json.load(f)

for doc in summary:
    print(f"\n--- {doc['document']} ---")
    for exp in doc["experiments"]:
        print(f"  Teste {exp['test_id']:02d} ({exp['strategy']:<20}) -> {exp['num_chunks']:>5} chunks | tam. médio: {exp['avg_chunk_size']:>7} | min: {exp['min_chunk_size']:>5} | max: {exp['max_chunk_size']:>5}")

totais_por_teste = defaultdict(int)
for doc in summary:
    for exp in doc["experiments"]:
        totais_por_teste[exp["test_id"]] += exp["num_chunks"]

mais_chunks = max(totais_por_teste, key=totais_por_teste.get)
menos_chunks = min(totais_por_teste, key=totais_por_teste.get)

print("\n" + "="*70)
print("Total de chunks por teste (somando todos os documentos):")
for t in sorted(totais_por_teste):
    print(f"  Teste {t:02d}: {totais_por_teste[t]} chunks")

print(f"\nTeste que MAIS gerou chunks: Teste {mais_chunks} ({totais_por_teste[mais_chunks]} chunks)")
print(f"Teste que MENOS gerou chunks: Teste {menos_chunks} ({totais_por_teste[menos_chunks]} chunks)")

======================================================================
RESUMO GERAL (do summary.json)
======================================================================

--- bioetica_e_ia.pdf ---
  Teste 01 (fixed               ) ->   269 chunks | tam. médio:   199.0 | min:    17 | max:   200
  Teste 02 (fixed               ) ->   108 chunks | tam. médio:   496.2 | min:   117 | max:   500
  Teste 03 (fixed               ) ->    54 chunks | tam. médio:   992.7 | min:   617 | max:  1000
  Teste 04 (fixed               ) ->    27 chunks | tam. médio:  1985.6 | min:  1617 | max:  2000
  Teste 05 (fixed_with_overlap  ) ->   120 chunks | tam. médio:   496.1 | min:    67 | max:   500
  Teste 06 (fixed_with_overlap  ) ->   179 chunks | tam. médio:   498.1 | min:   216 | max:   500
  Teste 07 (by_paragraph        ) ->     1 chunks | tam. médio: 53617.0 | min: 53617 | max: 53617
  Teste 08 (by_sentence_group3  ) ->   142 chunks | tam. médio:   375.6 | min:    36 | max:  1133
  Teste 09 (recursive           ) ->    73 chunks | tam. médio:   755.5 | min:    16 | max:   998
  Teste 10 (markdown_headers    ) ->    19 chunks | tam. médio:  2770.7 | min:   115 | max:  8779

--- escrita_academica_ia.pdf ---
  Teste 01 (fixed               ) ->   235 chunks | tam. médio:   199.1 | min:    82 | max:   200
  Teste 02 (fixed               ) ->    94 chunks | tam. médio:   498.4 | min:   382 | max:   500
  Teste 03 (fixed               ) ->    47 chunks | tam. médio:   997.0 | min:   881 | max:  1000
  Teste 04 (fixed               ) ->    24 chunks | tam. médio:  1953.0 | min:   881 | max:  2000
  Teste 05 (fixed_with_overlap  ) ->   105 chunks | tam. médio:   495.6 | min:    82 | max:   500
  Teste 06 (fixed_with_overlap  ) ->   156 chunks | tam. médio:   498.9 | min:   382 | max:   500
  Teste 07 (by_paragraph        ) ->     1 chunks | tam. médio: 46866.0 | min: 46866 | max: 46866
  Teste 08 (by_sentence_group3  ) ->    92 chunks | tam. médio:   507.2 | min:    88 | max:  1490
  Teste 09 (recursive           ) ->    73 chunks | tam. médio:   661.8 | min:    30 | max:   999
  Teste 10 (markdown_headers    ) ->    20 chunks | tam. médio:  2294.8 | min:    28 | max:  6749

--- twitter_algoritmo.pdf ---
  Teste 01 (fixed               ) ->   295 chunks | tam. médio:   199.6 | min:   178 | max:   200
  Teste 02 (fixed               ) ->   118 chunks | tam. médio:   499.5 | min:   478 | max:   500
  Teste 03 (fixed               ) ->    59 chunks | tam. médio:   999.4 | min:   978 | max:  1000
  Teste 04 (fixed               ) ->    30 chunks | tam. médio:  1965.7 | min:   978 | max:  2000
  Teste 05 (fixed_with_overlap  ) ->   131 chunks | tam. médio:   499.4 | min:   478 | max:   500
  Teste 06 (fixed_with_overlap  ) ->   196 chunks | tam. médio:   499.5 | min:   478 | max:   500
  Teste 07 (by_paragraph        ) ->     1 chunks | tam. médio: 58924.0 | min: 58924 | max: 58924
  Teste 08 (by_sentence_group3  ) ->   122 chunks | tam. médio:   480.4 | min:    37 | max:  2192
  Teste 09 (recursive           ) ->    80 chunks | tam. médio:   750.0 | min:   147 | max:   997
  Teste 10 (markdown_headers    ) ->    19 chunks | tam. médio:  3052.5 | min:   144 | max: 10064

--- attention_is_all_you_need.pdf ---
  Teste 01 (fixed               ) ->   212 chunks | tam. médio:   199.1 | min:   104 | max:   200
  Teste 02 (fixed               ) ->    85 chunks | tam. médio:   497.4 | min:   304 | max:   500
  Teste 03 (fixed               ) ->    43 chunks | tam. médio:   983.5 | min:   304 | max:  1000
  Teste 04 (fixed               ) ->    22 chunks | tam. médio:  1922.6 | min:   304 | max:  2000
  Teste 05 (fixed_with_overlap  ) ->    94 chunks | tam. médio:   499.2 | min:   454 | max:   500
  Teste 06 (fixed_with_overlap  ) ->   141 chunks | tam. médio:   498.2 | min:   304 | max:   500
  Teste 07 (by_paragraph        ) ->     1 chunks | tam. médio: 42274.0 | min: 42274 | max: 42274
  Teste 08 (by_sentence_group3  ) ->   119 chunks | tam. médio:   352.6 | min:    62 | max:  1329
  Teste 09 (recursive           ) ->    53 chunks | tam. médio:   809.5 | min:   242 | max:   995
  Teste 10 (markdown_headers    ) ->    26 chunks | tam. médio:  1590.8 | min:    58 | max:  8519

--- bert_pretraining.pdf ---
  Teste 01 (fixed               ) ->   332 chunks | tam. médio:   199.5 | min:   131 | max:   200
  Teste 02 (fixed               ) ->   133 chunks | tam. médio:   498.4 | min:   331 | max:   500
  Teste 03 (fixed               ) ->    67 chunks | tam. médio:   989.7 | min:   331 | max:  1000
  Teste 04 (fixed               ) ->    34 chunks | tam. médio:  1950.8 | min:   331 | max:  2000
  Teste 05 (fixed_with_overlap  ) ->   148 chunks | tam. médio:   497.4 | min:   181 | max:   500
  Teste 06 (fixed_with_overlap  ) ->   221 chunks | tam. médio:   498.9 | min:   331 | max:   500
  Teste 07 (by_paragraph        ) ->     1 chunks | tam. médio: 66305.0 | min: 66305 | max: 66305
  Teste 08 (by_sentence_group3  ) ->   193 chunks | tam. médio:   340.9 | min:    32 | max:  1208
  Teste 09 (recursive           ) ->    86 chunks | tam. médio:   782.4 | min:   136 | max:   997
  Teste 10 (markdown_headers    ) ->    31 chunks | tam. médio:  2090.3 | min:    69 | max: 11550

--- gpt3_language_models.pdf ---
  Teste 01 (fixed               ) ->  1318 chunks | tam. médio:   199.5 | min:    12 | max:   200
  Teste 02 (fixed               ) ->   527 chunks | tam. médio:   499.5 | min:   412 | max:   500
  Teste 03 (fixed               ) ->   264 chunks | tam. médio:   997.5 | min:   412 | max:  1000
  Teste 04 (fixed               ) ->   132 chunks | tam. médio:  1995.2 | min:  1412 | max:  2000
  Teste 05 (fixed_with_overlap  ) ->   586 chunks | tam. médio:   499.1 | min:   161 | max:   500
  Teste 06 (fixed_with_overlap  ) ->   878 chunks | tam. médio:   499.4 | min:   312 | max:   500
  Teste 07 (by_paragraph        ) ->     3 chunks | tam. médio: 87713.3 | min: 65614 | max: 99035
  Teste 08 (by_sentence_group3  ) ->   779 chunks | tam. médio:   336.0 | min:     5 | max:  6044
  Teste 09 (recursive           ) ->   365 chunks | tam. médio:   737.6 | min:     2 | max:   999
  Teste 10 (markdown_headers    ) ->    63 chunks | tam. médio:  4138.9 | min:   149 | max: 28308

--- gpt4_technical_report.pdf ---
  Teste 01 (fixed               ) ->  1476 chunks | tam. médio:   199.6 | min:   137 | max:   200
  Teste 02 (fixed               ) ->   591 chunks | tam. médio:   499.1 | min:   137 | max:   500
  Teste 03 (fixed               ) ->   296 chunks | tam. médio:   996.8 | min:   137 | max:  1000
  Teste 04 (fixed               ) ->   148 chunks | tam. médio:  1993.9 | min:  1136 | max:  2000
  Teste 05 (fixed_with_overlap  ) ->   656 chunks | tam. médio:   499.5 | min:   386 | max:   500
  Teste 06 (fixed_with_overlap  ) ->   984 chunks | tam. médio:   499.4 | min:   237 | max:   500
  Teste 07 (by_paragraph        ) ->     3 chunks | tam. médio: 98349.7 | min: 95637 | max: 99992
  Teste 08 (by_sentence_group3  ) ->   628 chunks | tam. médio:   467.1 | min:    31 | max: 18703
  Teste 09 (recursive           ) ->   397 chunks | tam. médio:   762.6 | min:     2 | max:   999
  Teste 10 (markdown_headers    ) ->    97 chunks | tam. médio:  2994.3 | min:    35 | max: 22982

--- instruct_gpt.pdf ---
  Teste 01 (fixed               ) ->   962 chunks | tam. médio:   199.5 | min:    58 | max:   200
  Teste 02 (fixed               ) ->   385 chunks | tam. médio:   499.0 | min:   258 | max:   500
  Teste 03 (fixed               ) ->   193 chunks | tam. médio:   995.8 | min:   258 | max:  1000
  Teste 04 (fixed               ) ->    97 chunks | tam. médio:  1981.6 | min:   258 | max:  2000
  Teste 05 (fixed_with_overlap  ) ->   428 chunks | tam. médio:   498.8 | min:   108 | max:   500
  Teste 06 (fixed_with_overlap  ) ->   641 chunks | tam. médio:   499.3 | min:   258 | max:   500
  Teste 07 (by_paragraph        ) ->     2 chunks | tam. médio: 96076.5 | min: 92247 | max: 99906
  Teste 08 (by_sentence_group3  ) ->   468 chunks | tam. médio:   408.0 | min:     2 | max:  3684
  Teste 09 (recursive           ) ->   259 chunks | tam. médio:   759.3 | min:    21 | max:   999
  Teste 10 (markdown_headers    ) ->    54 chunks | tam. médio:  3514.1 | min:   149 | max: 21291

--- llama_foundation_models.pdf ---
  Teste 01 (fixed               ) ->   461 chunks | tam. médio:   199.4 | min:   111 | max:   200
  Teste 02 (fixed               ) ->   185 chunks | tam. médio:   497.5 | min:   111 | max:   500
  Teste 03 (fixed               ) ->    93 chunks | tam. médio:   990.1 | min:   111 | max:  1000
  Teste 04 (fixed               ) ->    47 chunks | tam. médio:  1959.4 | min:   111 | max:  2000
  Teste 05 (fixed_with_overlap  ) ->   205 chunks | tam. médio:   498.6 | min:   311 | max:   500
  Teste 06 (fixed_with_overlap  ) ->   307 chunks | tam. médio:   499.0 | min:   311 | max:   500
  Teste 07 (by_paragraph        ) ->     1 chunks | tam. médio: 92073.0 | min: 92073 | max: 92073
  Teste 08 (by_sentence_group3  ) ->   295 chunks | tam. médio:   309.9 | min:    51 | max:  1846
  Teste 09 (recursive           ) ->   120 chunks | tam. médio:   780.3 | min:   143 | max:   997
  Teste 10 (markdown_headers    ) ->    51 chunks | tam. médio:  1758.4 | min:   145 | max: 21626

--- lora_low_rank_adaptation.pdf ---
  Teste 01 (fixed               ) ->   452 chunks | tam. médio:   199.3 | min:    38 | max:   200
  Teste 02 (fixed               ) ->   181 chunks | tam. médio:   498.3 | min:   238 | max:   500
  Teste 03 (fixed               ) ->    91 chunks | tam. médio:   991.4 | min:   238 | max:  1000
  Teste 04 (fixed               ) ->    46 chunks | tam. médio:  1961.4 | min:   238 | max:  2000
  Teste 05 (fixed_with_overlap  ) ->   201 chunks | tam. médio:   498.4 | min:   238 | max:   500
  Teste 06 (fixed_with_overlap  ) ->   301 chunks | tam. médio:   498.8 | min:   238 | max:   500
  Teste 07 (by_paragraph        ) ->     1 chunks | tam. médio: 90174.0 | min: 90174 | max: 90174
  Teste 08 (by_sentence_group3  ) ->   249 chunks | tam. médio:   359.9 | min:    58 | max:  2289
  Teste 09 (recursive           ) ->   126 chunks | tam. médio:   731.2 | min:   140 | max:   999
  Teste 10 (markdown_headers    ) ->    38 chunks | tam. médio:  2333.6 | min:    87 | max: 13653

--- retrieval_augmented_generation.pdf ---
  Teste 01 (fixed               ) ->   365 chunks | tam. médio:   199.2 | min:    33 | max:   200
  Teste 02 (fixed               ) ->   146 chunks | tam. médio:   498.5 | min:   333 | max:   500
  Teste 03 (fixed               ) ->    73 chunks | tam. médio:   997.3 | min:   833 | max:  1000
  Teste 04 (fixed               ) ->    37 chunks | tam. médio:  1968.2 | min:   833 | max:  2000
  Teste 05 (fixed_with_overlap  ) ->   162 chunks | tam. médio:   499.0 | min:   383 | max:   500
  Teste 06 (fixed_with_overlap  ) ->   243 chunks | tam. médio:   498.6 | min:   233 | max:   500
  Teste 07 (by_paragraph        ) ->     1 chunks | tam. médio: 72809.0 | min: 72809 | max: 72809
  Teste 08 (by_sentence_group3  ) ->   210 chunks | tam. médio:   344.6 | min:    54 | max:  1417
  Teste 09 (recursive           ) ->   100 chunks | tam. médio:   738.1 | min:   120 | max:   997
  Teste 10 (markdown_headers    ) ->    20 chunks | tam. médio:  3602.7 | min:   105 | max: 23641

--- scaling_laws_llm.pdf ---
  Teste 01 (fixed               ) ->   478 chunks | tam. médio:   199.4 | min:   111 | max:   200
  Teste 02 (fixed               ) ->   192 chunks | tam. médio:   497.1 | min:    11 | max:   500
  Teste 03 (fixed               ) ->    96 chunks | tam. médio:   994.6 | min:   511 | max:  1000
  Teste 04 (fixed               ) ->    48 chunks | tam. médio:  1989.6 | min:  1511 | max:  2000
  Teste 05 (fixed_with_overlap  ) ->   213 chunks | tam. médio:   497.8 | min:   111 | max:   500
  Teste 06 (fixed_with_overlap  ) ->   318 chunks | tam. médio:   499.3 | min:   411 | max:   500
  Teste 07 (by_paragraph        ) ->     1 chunks | tam. médio: 95355.0 | min: 95355 | max: 95355
  Teste 08 (by_sentence_group3  ) ->   464 chunks | tam. médio:   204.2 | min:     5 | max:  2367
  Teste 09 (recursive           ) ->   122 chunks | tam. médio:   794.7 | min:    30 | max:   997
  Teste 10 (markdown_headers    ) ->    19 chunks | tam. médio:  4981.6 | min:   241 | max: 13351

======================================================================
Total de chunks por teste (somando todos os documentos):
  Teste 01: 6855 chunks
  Teste 02: 2745 chunks
  Teste 03: 1376 chunks
  Teste 04: 692 chunks
  Teste 05: 3049 chunks
  Teste 06: 4565 chunks
  Teste 07: 17 chunks
  Teste 08: 3761 chunks
  Teste 09: 1854 chunks
  Teste 10: 457 chunks

Teste que MAIS gerou chunks: Teste 1 (6855 chunks)
Teste que MENOS gerou chunks: Teste 7 (17 chunks)

In [40]:
for doc in summary:
    for exp in doc["experiments"]:
        if exp["test_id"] == 7:
            print(f"{doc['document']:35} -> {exp['num_chunks']:>3} chunks | médio: {exp['avg_chunk_size']:>8} | max: {exp['max_chunk_size']:>8}")

bioetica_e_ia.pdf                   ->   1 chunks | médio:  53617.0 | max:    53617
escrita_academica_ia.pdf            ->   1 chunks | médio:  46866.0 | max:    46866
twitter_algoritmo.pdf               ->   1 chunks | médio:  58924.0 | max:    58924
attention_is_all_you_need.pdf       ->   1 chunks | médio:  42274.0 | max:    42274
bert_pretraining.pdf                ->   1 chunks | médio:  66305.0 | max:    66305
gpt3_language_models.pdf            ->   3 chunks | médio:  87713.3 | max:    99035
gpt4_technical_report.pdf           ->   3 chunks | médio:  98349.7 | max:    99992
instruct_gpt.pdf                    ->   2 chunks | médio:  96076.5 | max:    99906
llama_foundation_models.pdf         ->   1 chunks | médio:  92073.0 | max:    92073
lora_low_rank_adaptation.pdf        ->   1 chunks | médio:  90174.0 | max:    90174
retrieval_augmented_generation.pdf  ->   1 chunks | médio:  72809.0 | max:    72809
scaling_laws_llm.pdf                ->   1 chunks | médio:  95355.0 | max:    95355

In [41]:
for test_id in [3, 10]:
    with open(f"{PASTA_RESULTADOS}/bioetica_e_ia/test_{test_id:02d}/chunks_embeddings.json",
              encoding="utf-8") as f:
        chunks = json.load(f)
    print(f"\n===== Exemplos do Teste {test_id} =====")
    for c in chunks[:2]:
        print(f"\nchunk_id: {c['chunk_id']}")
        print(f"metadata: {c['metadata']}")
        print(f"texto (primeiros 300 caracteres): {c['text'][:300]}...")

===== Exemplos do Teste 3 =====

chunk_id: bioetica_e_ia_test03_chunk001
metadata: {}
texto (primeiros 300 caracteres): Revista Bioética

Print version ISSN 1983-8042 | On-line version ISSN 1983-8034

Rev. Bioét. vol.34 Brasília 2026

# **Entre o algoritmo e o Juramento de Hipócrates: bioética na era da inteligência artificial**

_Juracy Barbosa dos Santos_<sup>1</sup> _, Guilhermina Rego_<sup>1</sup> _, Rui Nune...

chunk_id: bioetica_e_ia_test03_chunk002
metadata: {}
texto (primeiros 300 caracteres): ipócrates. A incorporação da inteligência artificial na medicina suscita tensões entre eficiência automatizada e valores humanos. Este artigo revisa a literatura sobre os principais dilemas éticos da aplicação da inteligência artificial na prática médica e avalia em que medida os princípios hipocrát...

===== Exemplos do Teste 10 =====

chunk_id: bioetica_e_ia_test10_chunk001
metadata: {}
texto (primeiros 300 caracteres): Revista Bioética
Print version ISSN 1983-8042 | On-line version ISSN 1983-8034
Rev. Bioét. vol.34 Brasília 2026...

chunk_id: bioetica_e_ia_test10_chunk002
metadata: {'heading_1': '**Entre o algoritmo e o Juramento de Hipócrates: bioética na era da inteligência artificial**'}
texto (primeiros 300 caracteres): _Juracy Barbosa dos Santos_<sup>1</sup> _, Guilhermina Rego_<sup>1</sup> _, Rui Nunes_<sup>1</sup>
**1.** Faculdade de Medicina da Universidade do Porto, Porto, Portugal....

In [42]:
import re

print(f"{'Documento':35} | {'Nº linhas c/ tabela (|)':>25} | {'Nº refs a imagem':>18}")
print("-"*85)

for nome_doc, texto_md in markdowns.items():
    # conta linhas que parecem linha de tabela markdown (têm pelo menos 2 barras |)
    linhas_tabela = [l for l in texto_md.split("\n") if l.count("|") >= 2]

    # conta referências de imagem no formato markdown ![alt](caminho)
    refs_imagem = re.findall(r'!\[.*?\]\(.*?\)', texto_md)

    print(f"{nome_doc:35} | {len(linhas_tabela):>25} | {len(refs_imagem):>18}")

Documento                           |   Nº linhas c/ tabela (|) |   Nº refs a imagem
-------------------------------------------------------------------------------------
attention_is_all_you_need           |                        56 |                  0
bert_pretraining                    |                        90 |                  0
bioetica_e_ia                       |                         0 |                  0
escrita_academica_ia                |                        16 |                  0
gpt3_language_models                |                       480 |                  0
gpt4_technical_report               |                       236 |                  0
instruct_gpt                        |                       341 |                  0
llama_foundation_models             |                       220 |                  0
lora_low_rank_adaptation            |                       222 |                  0
retrieval_augmented_generation      |                        41 |                  0
scaling_laws_llm                    |                        78 |                  0
twitter_algoritmo                   |                         0 |                  0

In [43]:
# Mostra um trecho de exemplo de tabela, se encontrar
for nome_doc, texto_md in markdowns.items():
    linhas = texto_md.split("\n")
    for i, l in enumerate(linhas):
        if l.count("|") >= 2 and "---" in linhas[i+1] if i+1 < len(linhas) else False:
            print(f"\n=== Exemplo de tabela encontrada em {nome_doc} ===")
            print("\n".join(linhas[i:i+5]))
            break

=== Exemplo de tabela encontrada em attention_is_all_you_need ===
|Layer Type|Complexity per Layer|Sequential<br>Operations|Maximum Path Length|
|---|---|---|---|
|Self-Attention|_O_(_n_<sup>2</sup> _· d_)|_O_(1)|_O_(1)|
|Recurrent|_O_(_n · d_<sup>2</sup>)|_O_(_n_)|_O_(_n_)|
|Convolutional|_O_(_k · n · d_<sup>2</sup>)|_O_(1)|_O_(_logk_(_n_))|

=== Exemplo de tabela encontrada em bert_pretraining ===
|Input|[CLS]|my|dog|is|cute|[SEP]|he|likes|play|##ing|[SEP]|
|---|---|---|---|---|---|---|---|---|---|---|---|
|Token<br>Embeddings|E[CLS]|Emy|Edog|Eis|Ecute|E[SEP]|Ehe|Elikes|Eplay|E##ing|E[SEP]|
|Segment<br>Embeddings|EA|EA|EA|EA|EA|EA|EB|EB|EB|EB|EB|
|Position<br>Embeddings|E0|E1|E2|E3|E4|E5|E6|E7|E8|E9|E10|

=== Exemplo de tabela encontrada em escrita_academica_ia ===
||**Fase**|**Foco Principal**|**Objetivo**|
|---|---|---|---|
|Pré-<br>escrita|1. Planejamento humano<br>para o uso de IA|Estruturação pré-IA, proteção de<br>dados e engenharia de_prompts_|Garantir a intenção autoral, proteger dados de<br>pesquisa e dominar princípios de interação com<br>IA.|
|Escrita|2. Escrita assistida e cu-<br>radoria crítica|_Brainstorming_, análise e revisão<br>contínua|Usar a IA para expandir ideias, aprofundar refle-<br>xão crítica e refinar progressivamente o conteúdo.|
||3. Apropriação e reescrita<br>autoral|Transformação e personalização<br>do texto|Infundir a voz, pensamento e estilo do autor, ga-<br>rantindo originalidade e evitando marcas algorít-<br>micas.|

=== Exemplo de tabela encontrada em gpt3_language_models ===
|**Tom B. Bro**|**wn**<sup>_∗_</sup><br>**Benjamin**|**Mann**<sup>_∗_</sup><br>**Nick R**|**yder**<sup>_∗_</sup><br>**Melanie Subbiah**<sup>_∗_</sup>|
|---|---|---|---|
|**Jared Kaplan**<sup>_†_</sup>|**Prafulla Dhariwal**|**Arvind Neelakantan**|**Pranav Shyam**<br>**Girish Sastry**|
|**Amanda Askell**|**Sandhini Agarwal**|**Ariel Herbert-Voss**|**Gretchen Krueger**<br>**Tom Henighan**|
|**Rewon Child**|**Aditya Ramesh**|**Daniel M. Ziegler**|**Jeffrey Wu**<br>**Clemens Winter**|

=== Exemplo de tabela encontrada em gpt4_technical_report ===
|Exam|GPT-4|GPT-4 (no vision)|GPT-3.5|
|---|---|---|---|
|Uniform Bar Exam (MBE+MEE+MPT)<br>LSAT|298 / 400 (~90th)<br>163 (~88th)|298 / 400 (~90th)<br>161 (~83rd)|213 / 400 (~10th)<br>149 (~40th)|
|SAT Evidence-Based Reading & Writing|710 / 800 (~93rd)|710 / 800 (~93rd)|670 / 800 (~87th)|
|SAT Math|700 / 800 (~89th)|690 / 800 (~89th)|590 / 800 (~70th)|

=== Exemplo de tabela encontrada em instruct_gpt ===
|**Use-case**|**(%)**|**Use-case**|**Prompt**|
|---|---|---|---|
|Generation|45.6%|Brainstorming|List five ideas for how to regain enthusiasm for my|
|Open QA<br>|12.4%<br>||career|
|Brainstorming<br>Chat<br>Rewrite|11.2%<br>8.4%<br>6.6%|Generation|Write a short story where a bear goes to the beach,<br>makes friends with a seal, and then returns home.|

=== Exemplo de tabela encontrada em llama_foundation_models ===
|Dataset<br>S|ampling prop.|Epochs|Disk size|
|---|---|---|---|
|CommonCrawl|67.0%|1.10|3.3 TB|
|C4|15.0%|1.06|783 GB|
|Github|4.5%|0.64|328 GB|

=== Exemplo de tabela encontrada em lora_low_rank_adaptation ===
|Batch Size<br>Sequence Length|32<br>512|16<br>256|1<br>128|
|---|---|---|---|
|_|_Θ_|_|0.5M|11M|11M|
|Fine-Tune/LoRA|1449.4_±_0.8|338.0_±_0.6|19.8_±_2.7|
|Adapter<sup>L</sup><br>|1482.0_±_1.0 (+2.2%)|354.8_±_0.5 (+5.0%)|23.9_±_2.1 (+20.7%)|

=== Exemplo de tabela encontrada em retrieval_augmented_generation ===
|Closed<br>Book|Model<br>T5-11B [52]<br>T5-11B+SSM[52]|NQ<br>34.5<br>36.6|TQA<br>- /50.1<br>- /60.5|WQ<br>37.4<br>44.7|CT<br>-<br>-|Model|Jeop<br>B-1|ardy<br> QB-1|MSM<br>R-L|ARCO <br>B-1|FVR3 <br>Label|FVR2<br>Acc.|
|---|---|---|---|---|---|---|---|---|---|---|---|---|
|Open|REALM [20]|40.4|- / -|40.7|46.8|SotA|-|-|**49.8* **|**49.9***|**76.8**|**92.2***|
|Book|DPR [26]|41.5|**57.9**/ -|41.1|50.6|BART|15.1|19.7|38.2|41.6|64.0|81.1|
||RAG-Token|44.1|55.2/66.1|**45.5**|50.0|RAG-Tok.|**17.3**|**22.2**|40.1|41.5|725|895|

=== Exemplo de tabela encontrada em scaling_laws_llm ===
|**1**|**Introduction**|**2**|
|---|---|---|
|**2**|**Background and Methods**|**6**|
|**3**|**Empirical Results and Basic Power Laws**|**7**|
|**4**|**Charting the Infinite Data Limit and Overfitting**|**10**|

In [44]:
import re

print(f"{'Documento':35} | {'Refs de imagem (![](...))':>28}")
print("-"*68)

for nome_doc, texto_md in markdowns.items():
    refs_imagem = re.findall(r'!\[.*?\]\(.*?\)', texto_md)
    print(f"{nome_doc:35} | {len(refs_imagem):>28}")

Documento                           |    Refs de imagem (![](...))
--------------------------------------------------------------------
attention_is_all_you_need           |                            0
bert_pretraining                    |                            0
bioetica_e_ia                       |                            0
escrita_academica_ia                |                            0
gpt3_language_models                |                            0
gpt4_technical_report               |                            0
instruct_gpt                        |                            0
llama_foundation_models             |                            0
lora_low_rank_adaptation            |                            0
retrieval_augmented_generation      |                            0
scaling_laws_llm                    |                            0
twitter_algoritmo                   |                            0

In [45]:
import pandas as pd

linhas = []
for doc in summary:
    nome_doc = doc["document"].replace(".pdf", "")
    for exp in doc["experiments"]:
        if exp["test_id"] in [1, 2, 3, 4, 5, 6]:
            pct_overlap = 0
            if exp["chunk_size"]:
                pct_overlap = round((exp["chunk_overlap"] / exp["chunk_size"]) * 100, 1)
            linhas.append({
                "documento": nome_doc,
                "teste": exp["test_id"],
                "chunk_size": exp["chunk_size"],
                "chunk_overlap": exp["chunk_overlap"],
                "percentual_overlap": pct_overlap,
                "num_chunks": exp["num_chunks"],
                "tamanho_medio": exp["avg_chunk_size"],
            })

df_stats = pd.DataFrame(linhas)
df_stats

,documento,teste,chunk_size,chunk_overlap,percentual_overlap,num_chunks,tamanho_medio
0,bioetica_e_ia,1,200,0,0.0,269,199.0
1,bioetica_e_ia,2,500,0,0.0,108,496.2
2,bioetica_e_ia,3,1000,0,0.0,54,992.7
3,bioetica_e_ia,4,2000,0,0.0,27,1985.6
4,bioetica_e_ia,5,500,50,10.0,120,496.1
...,...,...,...,...,...,...,...
67,scaling_laws_llm,2,500,0,0.0,192,497.1
68,scaling_laws_llm,3,1000,0,0.0,96,994.6
69,scaling_laws_llm,4,2000,0,0.0,48,1989.6
70,scaling_laws_llm,5,500,50,10.0,213,497.8
71,scaling_laws_llm,6,500,200,40.0,318,499.3

In [48]:
%%writefile /content/relatorio_temp.md
# Relatório — Avaliação de Estratégias de Chunking com LangChain

## 1. Configuração dos 10 testes

| Teste | Estratégia | chunk_size | chunk_overlap | Total de chunks (12 docs) |
|---|---|---|---|---|
| 1 | fixed | 200 | 0 | 6855 |
| 2 | fixed | 500 | 0 | 2745 |
| 3 | fixed | 1000 | 0 | 1376 |
| 4 | fixed | 2000 | 0 | 692 |
| 5 | fixed_with_overlap | 500 | 50 (10%) | 3049 |
| 6 | fixed_with_overlap | 500 | 200 (40%) | 4565 |
| 7 | by_paragraph (separador \n\n) | - | 0 | 17 |
| 8 | by_sentence_group3 | - | 0 | 3761 |
| 9 | recursive | 1000 | 100 | 1854 |
| 10 | markdown_headers | - | 0 | 457 |

Modelo de embedding usado: `sentence-transformers/all-MiniLM-L6-v2` (384 dimensões), mantido fixo em todos os 10 testes para garantir comparabilidade.

Extração PDF → Markdown feita com `pymupdf4llm`, de forma automatizada, para os 12 PDFs da pasta compartilhada pelo professor.

## 2. Análise da conversão PDF → Markdown

A extração com `pymupdf4llm` preservou bem os elementos textuais: títulos ficaram marcados com `#`/`##`, formatação em negrito/itálico foi mantida (`**texto**`, `_texto_`), e até elementos como superscript (`<sup>`) foram preservados — o que ajudou o Markdown Header Splitter (Teste 10) a capturar corretamente os headings nos metadados (ex.: heading_1: "Entre o algoritmo e o Juramento de Hipócrates...").

Por outro lado, dois pontos ficaram claramente prejudicados:

- **Quebras de parágrafo**: o texto extraído não preserva quebras de linha dupla entre parágrafos de forma consistente — o que fez o Teste 7 (chunking por parágrafo) praticamente não dividir o texto (ver seção 4, pergunta 9).
- **Imagens**: nenhuma imagem foi referenciada em nenhum dos 12 documentos (0 ocorrências de referências de imagem em todos). As figuras dos PDFs (ex.: diagramas de arquitetura em attention_is_all_you_need, gráficos em scaling_laws_llm) foram completamente descartadas na extração — não há sequer uma marcação de posição indicando que ali existia uma figura.

## 3. Análise de tabelas

As tabelas foram convertidas para o formato Markdown padrão, mas com qualidade variável dependendo da complexidade do layout original:

- **Boa preservação**: tabelas simples e bem estruturadas no PDF original, como em bert_pretraining (tabela de embeddings token/segmento/posição) e attention_is_all_you_need (tabela de complexidade por tipo de camada), saíram legíveis e com a estrutura semântica mantida.
- **Preservação problemática**: em documentos com layout mais complexo (colunas duplas, tabelas lado a lado, ou blocos de texto que se assemelham a tabelas), a extração confundiu estrutura visual com tabela real. Exemplos:
  - Em gpt3_language_models, a lista de autores do paper (organizada em colunas no PDF) foi convertida como se fosse uma tabela de dados.
  - Em retrieval_augmented_generation, duas tabelas de resultados distintas do PDF (lado a lado) foram mescladas em uma única tabela Markdown, misturando colunas de contextos diferentes.
  - Em scaling_laws_llm, o próprio sumário do paper (número da seção + título + página) foi interpretado como tabela.

Isso mostra que a extração automática por pymupdf4llm é confiável para tabelas de dados simples, mas não distingue bem layout multi-coluna de tabela semântica real — um ponto de atenção para qualquer pipeline de RAG que dependa de tabelas extraídas.

## 4. Respostas às 15 perguntas do enunciado

**1. Qual estratégia gerou mais chunks?**
O Teste 1 (fixo, 200 caracteres, sem overlap), com 6855 chunks no total — esperado, já que é o menor tamanho de chunk configurado.

**2. Qual gerou menos chunks?**
O Teste 7 (por parágrafo), com apenas 17 chunks no total para os 12 documentos — bem abaixo até do Teste 4 (2000 caracteres, 692 chunks), que era o esperado como "extremo baixo" em quantidade.

**3. Como o tamanho dos chunks variou?**
Do menor extremo (Teste 1, ~200 caracteres) ao maior extremo real (Teste 7, com chunks de até ~99.992 caracteres — nesse caso, o documento inteiro virando 1 a 3 chunks), a variação foi de mais de 400x entre estratégias. Os testes por tamanho fixo (1-6) tiveram tamanhos previsíveis e controlados; os testes por estrutura natural (7, 8, 9, 10) tiveram tamanhos irregulares, dependentes do conteúdo de cada documento.

**4. Qual estratégia preservou melhor a estrutura dos documentos?**
O Teste 10 (Markdown Header Splitter): os metadados capturam corretamente o heading da seção, permitindo saber exatamente de qual seção do documento cada chunk veio — algo que nenhum outro teste oferece nativamente.

**5. Como tabelas foram tratadas?**
Convertidas para formato Markdown, com boa fidelidade em tabelas simples e distorções em tabelas de layout complexo (colunas de autores, tabelas lado a lado mescladas, sumários interpretados como tabela) — ver seção 3.

**6. Como imagens foram tratadas?**
Completamente descartadas: 0 referências de imagem em qualquer um dos 12 documentos processados. Não há marcação de posição nem descrição textual — a informação visual é perdida integralmente na extração.

**7. Quais informações foram perdidas na conversão PDF → Markdown?**
Principalmente: (a) todo o conteúdo visual (figuras, diagramas, gráficos); (b) a granularidade de parágrafos (quebras duplas não preservadas de forma consistente); (c) a distinção entre tabela de dados real e blocos de texto organizados visualmente em colunas.

**8. O chunking por caracteres fragmentou conceitos ou estruturas importantes?**
Sim, especialmente nos testes de

Writing /content/relatorio_temp.md

In [49]:
import shutil
shutil.copy("/content/relatorio_temp.md", "/content/drive/MyDrive/Residencia_RAG/relatorio.md")
print("relatorio.md salvo com sucesso na sua pasta do Drive!")

relatorio.md salvo com sucesso na sua pasta do Drive!

In [51]:
import tiktoken
import json

encoding = tiktoken.get_encoding("cl100k_base")

def contar_tokens(texto):
    # disallowed_special=() faz o tiktoken tratar qualquer coisa como texto normal,
    # mesmo que pareça um token especial como <|endofprompt|>
    return len(encoding.encode(texto, disallowed_special=()))

linhas_tokens = []

for doc in summary:
    nome_doc = doc["document"].replace(".pdf", "")
    for exp in doc["experiments"]:
        if exp["test_id"] in [1, 2, 3, 4, 5, 6]:
            caminho = f"{PASTA_RESULTADOS}/{nome_doc}/test_{exp['test_id']:02d}/chunks_embeddings.json"
            with open(caminho, encoding="utf-8") as f:
                chunks = json.load(f)

            tokens_por_chunk = [contar_tokens(c["text"]) for c in chunks]
            media_tokens = sum(tokens_por_chunk) / len(tokens_por_chunk) if tokens_por_chunk else 0

            linhas_tokens.append({
                "documento": nome_doc,
                "teste": exp["test_id"],
                "chunk_size": exp["chunk_size"],
                "num_chunks": exp["num_chunks"],
                "media_tokens": round(media_tokens, 1),
            })

    print(f"{nome_doc} processado.")

print("\nConcluído! Veja df_tokens abaixo.")

bioetica_e_ia processado.
escrita_academica_ia processado.
twitter_algoritmo processado.
attention_is_all_you_need processado.
bert_pretraining processado.
gpt3_language_models processado.
gpt4_technical_report processado.
instruct_gpt processado.
llama_foundation_models processado.
lora_low_rank_adaptation processado.
retrieval_augmented_generation processado.
scaling_laws_llm processado.

Concluído! Veja df_tokens abaixo.

In [52]:
import pandas as pd

df_tokens = pd.DataFrame(linhas_tokens)

media_por_teste = df_tokens.groupby("teste")["media_tokens"].mean().round(1)
print("Média de tokens por chunk, por teste (geral):")
print(media_por_teste)

df_tokens

Média de tokens por chunk, por teste (geral):
teste
1     56.0
2    138.6
3    275.7
4    545.4
5    138.6
6    138.9
Name: media_tokens, dtype: float64

           documento  teste  chunk_size  num_chunks  media_tokens
0      bioetica_e_ia      1         200         269          56.8
1      bioetica_e_ia      2         500         108         140.5
2      bioetica_e_ia      3        1000          54         280.3
3      bioetica_e_ia      4        2000          27         559.7
4      bioetica_e_ia      5         500         120         140.2
..               ...    ...         ...         ...           ...
67  scaling_laws_llm      2         500         192         136.4
68  scaling_laws_llm      3        1000          96         271.8
69  scaling_laws_llm      4        2000          48         542.9
70  scaling_laws_llm      5         500         213         136.5
71  scaling_laws_llm      6         500         318         136.5

[72 rows x 5 columns]

In [53]:
secao_tokens = """

## 7. Contagem de tokens (testes 1 a 6)

Utilizando o tokenizador `cl100k_base` (tiktoken), a média de tokens por chunk cresceu
de forma proporcional ao `chunk_size` configurado, como esperado (~4 caracteres por
token em média):

| Teste | chunk_size | chunk_overlap | Média de tokens/chunk |
|---|---|---|---|
| 1 | 200 | 0 | 56.0 |
| 2 | 500 | 0 | 138.6 |
| 3 | 1000 | 0 | 275.7 |
| 4 | 2000 | 0 | 545.4 |
| 5 | 500 | 50 | 138.6 |
| 6 | 500 | 200 | 138.9 |

Um ponto interessante: os Testes 2, 5 e 6 usam o mesmo `chunk_size` (500 caracteres),
mas variam o overlap — e a média de tokens por chunk ficou praticamente idêntica entre
eles (138.6, 138.6, 138.9). Isso é esperado, já que o overlap não altera o tamanho de
cada chunk individual, apenas quanto de conteúdo se repete entre chunks consecutivos
(o que se reflete no número total de chunks gerados, não no tamanho médio de cada

SyntaxError: incomplete input (394825926.py, line 1)

In [55]:
%%writefile /content/secao_tokens_temp.md


## 7. Contagem de tokens (testes 1 a 6)

Utilizando o tokenizador cl100k_base (tiktoken), a média de tokens por chunk cresceu de forma proporcional ao chunk_size configurado, como esperado (~4 caracteres por token em média):

| Teste | chunk_size | chunk_overlap | Média de tokens/chunk |
|---|---|---|---|
| 1 | 200 | 0 | 56.0 |
| 2 | 500 | 0 | 138.6 |
| 3 | 1000 | 0 | 275.7 |
| 4 | 2000 | 0 | 545.4 |
| 5 | 500 | 50 | 138.6 |
| 6 | 500 | 200 | 138.9 |

Um ponto interessante: os Testes 2, 5 e 6 usam o mesmo chunk_size (500 caracteres), mas variam o overlap — e a média de tokens por chunk ficou praticamente idêntica entre eles (138.6, 138.6, 138.9). Isso é esperado, já que o overlap não altera o tamanho de cada chunk individual, apenas quanto de conteúdo se repete entre chunks consecutivos (o que se reflete no número total de chunks gerados, não no tamanho médio de cada um).

Isso confirma que os chunks do Teste 1 (200 caracteres, ~56 tokens em média) são pequenos demais para carregar contexto substancial isoladamente, enquanto os do Teste 4 (2000 caracteres, ~545 tokens) já se aproximam do limite de contexto recomendado para muitos embedding models, o que reforça a preferência por chunk sizes intermediários (como no Teste 3, ~276 tokens, ou nas estratégias estruturais como Recursive e Markdown Headers) para um sistema de RAG equilibrado.

Overwriting /content/secao_tokens_temp.md

In [56]:
with open("/content/secao_tokens_temp.md", "r", encoding="utf-8") as f:
    secao_tokens = f.read()

caminho_relatorio = "/content/drive/MyDrive/Residencia_RAG/relatorio.md"

with open(caminho_relatorio, "r", encoding="utf-8") as f:
    conteudo_atual = f.read()

with open(caminho_relatorio, "w", encoding="utf-8") as f:
    f.write(conteudo_atual + secao_tokens)

print("Seção de tokens adicionada ao relatorio.md com sucesso!")

Seção de tokens adicionada ao relatorio.md com sucesso!